-- CertMuse 一期数据库：画像与证据域
-- 前置：003_*.sql
-- 执行账号：本地数据库对象所有者（不得使用应用账号）
-- 事务：本文件整体事务；psql必须启用ON_ERROR_STOP
-- 失败处理：事务回滚，修正后从本文件重新执行
-- 验证：文件末尾检查本批表数量
\set ON_ERROR_STOP on
BEGIN;

CREATE TABLE cm_profile_settlement (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    exam_subject_id bigint NOT NULL,
    knowledge_point_id bigint NOT NULL,
    settlement_type varchar(20) NOT NULL,
    source_session_id bigint,
    source_attempt_id bigint,
    source_error_record_id bigint,
    source_verification_record_id bigint,
    scoring_revision_no integer,
    settlement_revision_no integer DEFAULT 1 NOT NULL,
    supersedes_settlement_id bigint,
    settlement_snapshot jsonb NOT NULL,
    entry_direct_ability numeric(12,8),
    evidence_count integer DEFAULT 0 NOT NULL,
    aggregate_evidence_value numeric(12,8),
    positive_ratio numeric(12,8),
    negative_ratio numeric(12,8),
    effective_impact_coefficient numeric(12,8),
    tentative_direct_ability numeric(12,8),
    final_direct_ability numeric(12,8),
    status varchar(20) DEFAULT 'collecting' NOT NULL,
    rule_version_id bigint NOT NULL,
    request_id varchar(100) NOT NULL,
    settled_time timestamptz,
    failure_reason text,
    status_changed_by bigint,
    status_changed_time timestamptz DEFAULT now() NOT NULL,
    status_reason text,
    create_time timestamptz DEFAULT now() NOT NULL,
    update_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_profile_settlement PRIMARY KEY (id),
    CONSTRAINT ck_cm_profile_settlement_entry_direct_ability CHECK (entry_direct_ability >= 0 AND entry_direct_ability <= 100),
    CONSTRAINT ck_cm_profile_settlement_evidence_count CHECK (evidence_count >= 0),
    CONSTRAINT ck_cm_profile_settlement_aggregate_evidence_value CHECK (aggregate_evidence_value >= 0 AND aggregate_evidence_value <= 100),
    CONSTRAINT ck_cm_profile_settlement_positive_ratio CHECK (positive_ratio >= 0 AND positive_ratio <= 1),
    CONSTRAINT ck_cm_profile_settlement_negative_ratio CHECK (negative_ratio >= 0 AND negative_ratio <= 1),
    CONSTRAINT ck_cm_profile_settlement_tentative_direct_ability CHECK (tentative_direct_ability >= 0 AND tentative_direct_ability <= 100),
    CONSTRAINT ck_cm_profile_settlement_final_direct_ability CHECK (final_direct_ability >= 0 AND final_direct_ability <= 100),
    CONSTRAINT uk_cm_profile_settlement_request_id UNIQUE (request_id)
);

CREATE TABLE cm_learning_evidence (
    id bigint NOT NULL,
    settlement_id bigint NOT NULL,
    user_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    session_id bigint NOT NULL,
    attempt_id bigint NOT NULL,
    scoring_point_snapshot jsonb DEFAULT '{"schema_version":"2.0","snapshot_type":"evidence","items":[]}'::jsonb NOT NULL,
    exam_subject_id bigint NOT NULL,
    knowledge_point_id bigint NOT NULL,
    evidence_group_key varchar(100) NOT NULL,
    behavior_type varchar(30) NOT NULL,
    difficulty_snapshot varchar(20) NOT NULL,
    score_rate numeric(12,8),
    raw_evidence_value numeric(12,8),
    direction varchar(20) NOT NULL,
    hint_level varchar(20) DEFAULT 'none' NOT NULL,
    elapsed_seconds integer,
    timer_status varchar(20) NOT NULL,
    hint_coefficient numeric(12,8) DEFAULT 1 NOT NULL,
    time_coefficient numeric(12,8) DEFAULT 1 NOT NULL,
    combined_coefficient numeric(12,8) DEFAULT 1 NOT NULL,
    behavior_coefficient numeric(12,8) DEFAULT 0 NOT NULL,
    streak_coefficient numeric(12,8) DEFAULT 1 NOT NULL,
    is_regression_evidence boolean DEFAULT false NOT NULL,
    regression_interval_days integer,
    regression_coefficient numeric(12,8) DEFAULT 1 NOT NULL,
    is_first_encounter boolean DEFAULT false NOT NULL,
    is_distinct_question boolean DEFAULT false NOT NULL,
    is_independent_verification boolean DEFAULT false NOT NULL,
    is_valid boolean DEFAULT true NOT NULL,
    invalid_reason text,
    rule_version_id bigint NOT NULL,
    answered_at timestamptz NOT NULL,
    effective_at timestamptz NOT NULL,
    settlement_sequence bigint NOT NULL,
    create_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_learning_evidence PRIMARY KEY (id),
    CONSTRAINT ck_cm_learning_evidence_difficulty_snapshot CHECK (difficulty_snapshot IN ('easy','medium','hard')),
    CONSTRAINT ck_cm_learning_evidence_score_rate CHECK (score_rate >= 0 AND score_rate <= 1),
    CONSTRAINT ck_cm_learning_evidence_raw_evidence_value CHECK (raw_evidence_value >= 0 AND raw_evidence_value <= 100),
    CONSTRAINT ck_cm_learning_evidence_elapsed_seconds CHECK (elapsed_seconds >= 0),
    CONSTRAINT ck_cm_learning_evidence_hint_coefficient CHECK (hint_coefficient >= 0 AND hint_coefficient <= 1),
    CONSTRAINT ck_cm_learning_evidence_combined_coefficient CHECK (combined_coefficient >= 0 AND combined_coefficient <= 1),
    CONSTRAINT ck_cm_learning_evidence_streak_coefficient CHECK (streak_coefficient >= 1 AND streak_coefficient <= 1.15),
    CONSTRAINT ck_cm_learning_evidence_regression_interval_days CHECK (regression_interval_days >= 0),
    CONSTRAINT ck_cm_learning_evidence_regression_coefficient CHECK (regression_coefficient IN (1.00,1.10,1.15))
);

CREATE TABLE cm_knowledge_profile (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    knowledge_point_id bigint NOT NULL,
    baseline_direct_ability numeric(12,8),
    current_direct_ability numeric(12,8),
    confidence_level varchar(20) DEFAULT 'unassessed' NOT NULL,
    freshness numeric(12,8),
    profile_status varchar(30) DEFAULT 'unassessed' NOT NULL,
    distinct_question_count integer DEFAULT 0 NOT NULL,
    last_direct_evidence_time timestamptz,
    recent_trend varchar(20) DEFAULT 'stable' NOT NULL,
    conflict_flag boolean DEFAULT false NOT NULL,
    pending_verification_flag boolean DEFAULT false NOT NULL,
    ever_mastered_flag boolean DEFAULT false NOT NULL,
    rule_version_id bigint NOT NULL,
    calculated_time timestamptz DEFAULT now() NOT NULL,
    next_recalculation_time timestamptz,
    row_version bigint DEFAULT 0 NOT NULL,
    create_time timestamptz DEFAULT now() NOT NULL,
    update_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_knowledge_profile PRIMARY KEY (id),
    CONSTRAINT ck_cm_knowledge_profile_baseline_direct_ability CHECK (baseline_direct_ability >= 0 AND baseline_direct_ability <= 100),
    CONSTRAINT ck_cm_knowledge_profile_current_direct_ability CHECK (current_direct_ability >= 0 AND current_direct_ability <= 100),
    CONSTRAINT ck_cm_knowledge_profile_distinct_question_count CHECK (distinct_question_count >= 0),
    CONSTRAINT ck_cm_knowledge_profile_row_version CHECK (row_version >= 0)
);

CREATE TABLE cm_profile_change (
    id bigint NOT NULL,
    profile_level varchar(20) NOT NULL,
    knowledge_profile_id bigint,
    subject_profile_id bigint,
    overall_profile_id bigint,
    settlement_id bigint,
    change_type varchar(30) NOT NULL,
    before_data jsonb,
    after_data jsonb NOT NULL,
    rule_version_id bigint NOT NULL,
    request_id varchar(100) NOT NULL,
    change_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_profile_change PRIMARY KEY (id),
    CONSTRAINT uk_cm_profile_change_request_id UNIQUE (request_id)
);

CREATE TABLE cm_subject_profile (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    exam_subject_id bigint NOT NULL,
    knowledge_aggregate_score numeric(12,8),
    subject_ability numeric(12,8),
    diagnosis_completion_rate numeric(12,8) DEFAULT 0 NOT NULL,
    target_coverage_rate numeric(12,8) DEFAULT 0 NOT NULL,
    medium_high_coverage_rate numeric(12,8) DEFAULT 0 NOT NULL,
    core_knowledge_covered boolean DEFAULT false NOT NULL,
    confidence_level varchar(20) DEFAULT 'unassessed' NOT NULL,
    conflict_flag boolean DEFAULT false NOT NULL,
    last_hint_free_verification_time timestamptz,
    efficiency_status varchar(30),
    efficiency_sample_count integer DEFAULT 0 NOT NULL,
    correct_time_ratio_median numeric(12,8),
    timeout_rate numeric(12,8),
    fast_wrong_rate numeric(12,8),
    time_risk_flag boolean DEFAULT false NOT NULL,
    guessing_risk_flag boolean DEFAULT false NOT NULL,
    rule_version_id bigint NOT NULL,
    calculated_time timestamptz DEFAULT now() NOT NULL,
    next_recalculation_time timestamptz,
    row_version bigint DEFAULT 0 NOT NULL,
    create_time timestamptz DEFAULT now() NOT NULL,
    update_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_subject_profile PRIMARY KEY (id),
    CONSTRAINT ck_cm_subject_profile_knowledge_aggregate_score CHECK (knowledge_aggregate_score >= 0 AND knowledge_aggregate_score <= 100),
    CONSTRAINT ck_cm_subject_profile_subject_ability CHECK (subject_ability >= 0 AND subject_ability <= 100),
    CONSTRAINT ck_cm_subject_profile_diagnosis_completion_rate CHECK (diagnosis_completion_rate >= 0 AND diagnosis_completion_rate <= 1),
    CONSTRAINT ck_cm_subject_profile_target_coverage_rate CHECK (target_coverage_rate >= 0 AND target_coverage_rate <= 1),
    CONSTRAINT ck_cm_subject_profile_medium_high_coverage_rate CHECK (medium_high_coverage_rate >= 0 AND medium_high_coverage_rate <= 1),
    CONSTRAINT ck_cm_subject_profile_efficiency_sample_count CHECK (efficiency_sample_count >= 0),
    CONSTRAINT ck_cm_subject_profile_correct_time_ratio_median CHECK (correct_time_ratio_median >= 0),
    CONSTRAINT ck_cm_subject_profile_timeout_rate CHECK (timeout_rate >= 0 AND timeout_rate <= 1),
    CONSTRAINT ck_cm_subject_profile_fast_wrong_rate CHECK (fast_wrong_rate >= 0 AND fast_wrong_rate <= 1),
    CONSTRAINT ck_cm_subject_profile_row_version CHECK (row_version >= 0)
);

CREATE TABLE cm_overall_profile (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    subject_snapshot jsonb DEFAULT '{"schema_version":"1.0","subjects":[]}'::jsonb NOT NULL,
    overall_ability numeric(12,8),
    profile_stage varchar(20) DEFAULT 'initial' NOT NULL,
    readiness_level varchar(20),
    gate_check_data jsonb DEFAULT '{"schema_version":"1.0","gates":[],"all_passed":false}'::jsonb NOT NULL,
    rule_version_id bigint NOT NULL,
    calculated_time timestamptz DEFAULT now() NOT NULL,
    next_recalculation_time timestamptz,
    row_version bigint DEFAULT 0 NOT NULL,
    create_time timestamptz DEFAULT now() NOT NULL,
    update_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_overall_profile PRIMARY KEY (id),
    CONSTRAINT uk_cm_overall_profile_goal_id UNIQUE (goal_id),
    CONSTRAINT ck_cm_overall_profile_overall_ability CHECK (overall_ability >= 0 AND overall_ability <= 100),
    CONSTRAINT ck_cm_overall_profile_row_version CHECK (row_version >= 0)
);

CREATE TABLE cm_learning_evidence_event (
    id bigint NOT NULL,
    evidence_id bigint NOT NULL,
    event_type varchar(20) NOT NULL,
    before_valid boolean NOT NULL,
    after_valid boolean NOT NULL,
    before_distinct boolean NOT NULL,
    after_distinct boolean NOT NULL,
    replacement_evidence_id bigint,
    reason_code varchar(50) NOT NULL,
    reason text NOT NULL,
    operator_id bigint,
    request_id varchar(100) NOT NULL,
    event_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_learning_evidence_event PRIMARY KEY (id),
    CONSTRAINT uk_cm_learning_evidence_event_request_id UNIQUE (request_id)
);

CREATE TABLE cm_profile_recalculation_job (
    id bigint NOT NULL,
    scope_type varchar(30) NOT NULL,
    scope_data jsonb NOT NULL,
    trigger_reason varchar(50) NOT NULL,
    old_rule_version_id bigint,
    new_rule_version_id bigint,
    status varchar(20) DEFAULT 'queued' NOT NULL,
    stage varchar(50),
    progress_percent numeric(5,2) DEFAULT 0 NOT NULL,
    total_count integer DEFAULT 0 NOT NULL,
    success_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    skipped_count integer DEFAULT 0 NOT NULL,
    request_id varchar(100) NOT NULL,
    trace_id varchar(100),
    retry_from_job_id bigint,
    started_time timestamptz,
    finished_time timestamptz,
    result_summary jsonb,
    failure_objects jsonb,
    status_changed_by bigint,
    status_changed_time timestamptz DEFAULT now() NOT NULL,
    status_reason text,
    create_time timestamptz DEFAULT now() NOT NULL,
    update_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_profile_recalculation_job PRIMARY KEY (id),
    CONSTRAINT ck_cm_profile_recalculation_job_progress_percent CHECK (progress_percent >= 0 AND progress_percent <= 100),
    CONSTRAINT ck_cm_profile_recalculation_job_total_count CHECK (total_count >= 0),
    CONSTRAINT ck_cm_profile_recalculation_job_success_count CHECK (success_count >= 0),
    CONSTRAINT ck_cm_profile_recalculation_job_failed_count CHECK (failed_count >= 0),
    CONSTRAINT ck_cm_profile_recalculation_job_skipped_count CHECK (skipped_count >= 0),
    CONSTRAINT uk_cm_profile_recalculation_job_request_id UNIQUE (request_id)
);

CREATE TABLE cm_profile_checkpoint (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    knowledge_point_id bigint NOT NULL,
    rule_version_id bigint NOT NULL,
    last_settlement_sequence bigint NOT NULL,
    checkpoint_data jsonb NOT NULL,
    checkpoint_time timestamptz DEFAULT now() NOT NULL,
    create_time timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_cm_profile_checkpoint PRIMARY KEY (id)
);

DO $$ BEGIN IF (SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_name = ANY (ARRAY['cm_profile_settlement','cm_learning_evidence','cm_knowledge_profile','cm_profile_change','cm_subject_profile','cm_overall_profile','cm_learning_evidence_event','cm_profile_recalculation_job','cm_profile_checkpoint'])) <> 9 THEN RAISE EXCEPTION 'CertMuse 004 table count mismatch'; END IF; END $$;
COMMIT;
