-- CertMuse 一期数据库：跨表约束、触发器、索引、权限与种子
-- 前置：001_foundation.sql 至 005_support.sql
-- 执行账号：本地数据库对象所有者（需要CREATE ROLE权限以创建本地权限组）
-- 事务：本文件整体事务；psql必须启用ON_ERROR_STOP
-- 失败处理：事务回滚，修正后重新执行本文件
-- 验证：文件末尾检查66表、65个id主键、自然主键、种子及权限组
\set ON_ERROR_STOP on
BEGIN;

ALTER TABLE cm_exam_subject ADD CONSTRAINT uk_cm_exam_subject_certification_id_subject_code UNIQUE (certification_id, subject_code);
ALTER TABLE cm_exam_subject ADD CONSTRAINT uk_cm_exam_subject_id_certification_id UNIQUE (id, certification_id);
ALTER TABLE cm_syllabus_version ADD CONSTRAINT uk_cm_syllabus_version_certification_id_version_name UNIQUE (certification_id, version_name);
ALTER TABLE cm_knowledge_point ADD CONSTRAINT uk_cm_knowledge_point_id_syllabus_version_id_exam_subject_id UNIQUE (id, syllabus_version_id, exam_subject_id);
ALTER TABLE cm_knowledge_point ADD CONSTRAINT uk_cm_knowledge_point_id_exam_subject_id UNIQUE (id, exam_subject_id);
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT uk_cm_knowledge_prerequisite_knowledge_point_id_prereq_4f5b62e3 UNIQUE (knowledge_point_id, prerequisite_knowledge_point_id);
ALTER TABLE cm_knowledge_misconception ADD CONSTRAINT uk_cm_knowledge_misconception_knowledge_point_id_misco_3696f0c7 UNIQUE (knowledge_point_id, misconception_id);
ALTER TABLE cm_question ADD CONSTRAINT uk_cm_question_id_exam_subject_id UNIQUE (id, exam_subject_id);
CREATE UNIQUE INDEX uk_cm_question_source_identity_hash ON cm_question(source_identity_hash) WHERE source_identity_hash IS NOT NULL AND del_flag = '0';
ALTER TABLE cm_question_revision ADD CONSTRAINT uk_cm_question_revision_question_id_revision_no UNIQUE (question_id, revision_no);
ALTER TABLE cm_question_revision ADD CONSTRAINT uk_cm_question_revision_id_question_id UNIQUE (id, question_id);
ALTER TABLE cm_question_revision_event ADD CONSTRAINT uk_cm_question_revision_event_request_id_question_revi_bbd66b63 UNIQUE (request_id, question_revision_id, event_type);
ALTER TABLE cm_question_option ADD CONSTRAINT uk_cm_question_option_question_revision_id_option_label UNIQUE (question_revision_id, option_label);
ALTER TABLE cm_question_image ADD CONSTRAINT uk_cm_question_image_question_revision_id_image_order UNIQUE (question_revision_id, image_order);
ALTER TABLE cm_question_knowledge ADD CONSTRAINT uk_cm_question_knowledge_question_revision_id_knowledg_16bb13e6 UNIQUE (question_revision_id, knowledge_point_id);
ALTER TABLE cm_document_chunk ADD CONSTRAINT uk_cm_document_chunk_document_id_chunk_order UNIQUE (document_id, chunk_order);
ALTER TABLE cm_document_image ADD CONSTRAINT uk_cm_document_image_chunk_id_image_order UNIQUE (chunk_id, image_order);
ALTER TABLE cm_chunk_knowledge ADD CONSTRAINT uk_cm_chunk_knowledge_chunk_id_knowledge_point_id UNIQUE (chunk_id, knowledge_point_id);
ALTER TABLE cm_import_record ADD CONSTRAINT uk_cm_import_record_batch_id_source_line_no UNIQUE (batch_id, source_line_no);
ALTER TABLE cm_question_scoring_point ADD CONSTRAINT uk_cm_question_scoring_point_question_revision_id_scoring_code UNIQUE (question_revision_id, scoring_code);
ALTER TABLE cm_question_scoring_point ADD CONSTRAINT uk_cm_question_scoring_point_question_revision_id_sort_order UNIQUE (question_revision_id, sort_order);
ALTER TABLE cm_scoring_point_knowledge ADD CONSTRAINT uk_cm_scoring_point_knowledge_scoring_point_id_knowled_7e6080e8 UNIQUE (scoring_point_id, knowledge_point_id);
ALTER TABLE cm_session_question ADD CONSTRAINT uk_cm_session_question_session_id_question_order UNIQUE (session_id, question_order);
ALTER TABLE cm_session_question ADD CONSTRAINT uk_cm_session_question_session_id_question_revision_id UNIQUE (session_id, question_revision_id);
ALTER TABLE cm_question_attempt ADD CONSTRAINT uk_cm_question_attempt_session_question_id_attempt_no UNIQUE (session_question_id, attempt_no);
ALTER TABLE cm_attempt_scoring_point ADD CONSTRAINT uk_cm_attempt_scoring_point_attempt_id_scoring_point_i_ec57b86f UNIQUE (attempt_id, scoring_point_id, knowledge_point_id);
ALTER TABLE cm_hint_usage ADD CONSTRAINT uk_cm_hint_usage_attempt_id_hint_order UNIQUE (attempt_id, hint_order);
ALTER TABLE cm_error_record ADD CONSTRAINT uk_cm_error_record_attempt_id_knowledge_point_id UNIQUE (attempt_id, knowledge_point_id);
ALTER TABLE cm_correction_record ADD CONSTRAINT uk_cm_correction_record_error_record_id_correction_attempt_id UNIQUE (error_record_id, correction_attempt_id);
ALTER TABLE cm_verification_record ADD CONSTRAINT uk_cm_verification_record_correction_record_id_verific_781007aa UNIQUE (correction_record_id, verification_attempt_id);
ALTER TABLE cm_task_item ADD CONSTRAINT uk_cm_task_item_task_id_item_order UNIQUE (task_id, item_order);
ALTER TABLE cm_task_reason ADD CONSTRAINT uk_cm_task_reason_task_item_id_reason_code UNIQUE (task_item_id, reason_code);
ALTER TABLE cm_task_attempt ADD CONSTRAINT uk_cm_task_attempt_task_item_id_attempt_no UNIQUE (task_item_id, attempt_no);
ALTER TABLE cm_knowledge_profile ADD CONSTRAINT uk_cm_knowledge_profile_user_id_goal_id_knowledge_point_id UNIQUE (user_id, goal_id, knowledge_point_id);
ALTER TABLE cm_subject_profile ADD CONSTRAINT uk_cm_subject_profile_user_id_goal_id_exam_subject_id UNIQUE (user_id, goal_id, exam_subject_id);
ALTER TABLE cm_overall_profile ADD CONSTRAINT uk_cm_overall_profile_user_id_goal_id UNIQUE (user_id, goal_id);
ALTER TABLE cm_profile_checkpoint ADD CONSTRAINT uk_cm_profile_checkpoint_user_id_goal_id_knowledge_poi_e4002a41 UNIQUE (user_id, goal_id, knowledge_point_id, last_settlement_sequence);
ALTER TABLE cm_exam_schedule ADD CONSTRAINT uk_cm_exam_schedule_certification_id_revision_no UNIQUE (certification_id, revision_no);
ALTER TABLE cm_exam_schedule_session ADD CONSTRAINT uk_cm_exam_schedule_session_exam_schedule_id_session_code UNIQUE (exam_schedule_id, session_code);
ALTER TABLE cm_exam_schedule_session ADD CONSTRAINT uk_cm_exam_schedule_session_exam_schedule_id_sort_order UNIQUE (exam_schedule_id, sort_order);
ALTER TABLE cm_collection ADD CONSTRAINT uk_cm_collection_certification_id_syllabus_version_id__540d302e UNIQUE (certification_id, syllabus_version_id, collection_code);
ALTER TABLE cm_collection_revision ADD CONSTRAINT uk_cm_collection_revision_collection_id_revision_no UNIQUE (collection_id, revision_no);
ALTER TABLE cm_collection_item ADD CONSTRAINT uk_cm_collection_item_collection_revision_id_item_order UNIQUE (collection_revision_id, item_order);
ALTER TABLE cm_collection_item ADD CONSTRAINT uk_cm_collection_item_collection_revision_id_question__2c0270c6 UNIQUE (collection_revision_id, question_revision_id);
ALTER TABLE cm_assessment_report ADD CONSTRAINT uk_cm_assessment_report_session_id_report_type UNIQUE (session_id, report_type);
ALTER TABLE cm_ai_scoring_job ADD CONSTRAINT uk_cm_ai_scoring_job_attempt_id_attempt_no UNIQUE (attempt_id, attempt_no);
ALTER TABLE cm_scoring_review ADD CONSTRAINT uk_cm_scoring_review_attempt_scoring_point_id_review_no UNIQUE (attempt_scoring_point_id, review_no);
ALTER TABLE cm_daily_task_batch ADD CONSTRAINT uk_cm_daily_task_batch_user_id_goal_id_task_date UNIQUE (user_id, goal_id, task_date);
ALTER TABLE cm_idempotency_record ADD CONSTRAINT uk_cm_idempotency_record_action_code_request_id UNIQUE (action_code, request_id);
ALTER TABLE cm_async_job ADD CONSTRAINT uk_cm_async_job_job_type_business_key UNIQUE (job_type, business_key);
ALTER TABLE cm_rule_hit ADD CONSTRAINT uk_cm_rule_hit_request_id_rule_code_target_type_target_id UNIQUE (request_id, rule_code, target_type, target_id);
ALTER TABLE cm_exam_subject ADD CONSTRAINT fk_cm_exam_subject_certification_id FOREIGN KEY (certification_id) REFERENCES cm_exam_certification(id) ON DELETE RESTRICT;
ALTER TABLE cm_syllabus_version ADD CONSTRAINT fk_cm_syllabus_version_certification_id FOREIGN KEY (certification_id) REFERENCES cm_exam_certification(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_point ADD CONSTRAINT fk_cm_knowledge_point_syllabus_version_id FOREIGN KEY (syllabus_version_id) REFERENCES cm_syllabus_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_point ADD CONSTRAINT fk_cm_knowledge_point_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_point ADD CONSTRAINT fk_cm_knowledge_point_parent_id FOREIGN KEY (parent_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT fk_cm_knowledge_prerequisite_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT fk_cm_knowledge_prerequisite_prerequisite_knowledge_point_id FOREIGN KEY (prerequisite_knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT fk_cm_knowledge_prerequisite_syllabus_version_id FOREIGN KEY (syllabus_version_id) REFERENCES cm_syllabus_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT fk_cm_knowledge_prerequisite_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_misconception ADD CONSTRAINT fk_cm_knowledge_misconception_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_misconception ADD CONSTRAINT fk_cm_knowledge_misconception_misconception_id FOREIGN KEY (misconception_id) REFERENCES cm_misconception(id) ON DELETE RESTRICT;
ALTER TABLE cm_question ADD CONSTRAINT fk_cm_question_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_question ADD CONSTRAINT fk_cm_question_copied_from_question_id FOREIGN KEY (copied_from_question_id) REFERENCES cm_question(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_revision ADD CONSTRAINT fk_cm_question_revision_question_id FOREIGN KEY (question_id) REFERENCES cm_question(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_revision_event ADD CONSTRAINT fk_cm_question_revision_event_question_id FOREIGN KEY (question_id) REFERENCES cm_question(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_revision_event ADD CONSTRAINT fk_cm_question_revision_event_question_revision_id FOREIGN KEY (question_revision_id) REFERENCES cm_question_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_option ADD CONSTRAINT fk_cm_question_option_question_revision_id FOREIGN KEY (question_revision_id) REFERENCES cm_question_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_image ADD CONSTRAINT fk_cm_question_image_question_revision_id FOREIGN KEY (question_revision_id) REFERENCES cm_question_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_knowledge ADD CONSTRAINT fk_cm_question_knowledge_question_revision_id FOREIGN KEY (question_revision_id) REFERENCES cm_question_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_knowledge ADD CONSTRAINT fk_cm_question_knowledge_question_id FOREIGN KEY (question_id) REFERENCES cm_question(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_knowledge ADD CONSTRAINT fk_cm_question_knowledge_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_knowledge ADD CONSTRAINT fk_cm_question_knowledge_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_document ADD CONSTRAINT fk_cm_document_syllabus_version_id FOREIGN KEY (syllabus_version_id) REFERENCES cm_syllabus_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_document_chunk ADD CONSTRAINT fk_cm_document_chunk_document_id FOREIGN KEY (document_id) REFERENCES cm_document(id) ON DELETE RESTRICT;
ALTER TABLE cm_document_image ADD CONSTRAINT fk_cm_document_image_chunk_id FOREIGN KEY (chunk_id) REFERENCES cm_document_chunk(id) ON DELETE RESTRICT;
ALTER TABLE cm_chunk_knowledge ADD CONSTRAINT fk_cm_chunk_knowledge_chunk_id FOREIGN KEY (chunk_id) REFERENCES cm_document_chunk(id) ON DELETE RESTRICT;
ALTER TABLE cm_chunk_knowledge ADD CONSTRAINT fk_cm_chunk_knowledge_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_batch ADD CONSTRAINT fk_cm_import_batch_retry_from_batch_id FOREIGN KEY (retry_from_batch_id) REFERENCES cm_import_batch(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_batch ADD CONSTRAINT fk_cm_import_batch_document_id FOREIGN KEY (document_id) REFERENCES cm_document(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_batch ADD CONSTRAINT fk_cm_import_batch_syllabus_version_id FOREIGN KEY (syllabus_version_id) REFERENCES cm_syllabus_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_batch ADD CONSTRAINT fk_cm_import_batch_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_record ADD CONSTRAINT fk_cm_import_record_batch_id FOREIGN KEY (batch_id) REFERENCES cm_import_batch(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_record ADD CONSTRAINT fk_cm_import_record_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_record ADD CONSTRAINT fk_cm_import_record_retry_of_record_id FOREIGN KEY (retry_of_record_id) REFERENCES cm_import_record(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_scoring_point ADD CONSTRAINT fk_cm_question_scoring_point_question_revision_id FOREIGN KEY (question_revision_id) REFERENCES cm_question_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_scoring_point_knowledge ADD CONSTRAINT fk_cm_scoring_point_knowledge_scoring_point_id FOREIGN KEY (scoring_point_id) REFERENCES cm_question_scoring_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_scoring_point_knowledge ADD CONSTRAINT fk_cm_scoring_point_knowledge_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_user_goal ADD CONSTRAINT fk_cm_user_goal_certification_id FOREIGN KEY (certification_id) REFERENCES cm_exam_certification(id) ON DELETE RESTRICT;
ALTER TABLE cm_user_goal ADD CONSTRAINT fk_cm_user_goal_syllabus_version_id FOREIGN KEY (syllabus_version_id) REFERENCES cm_syllabus_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_user_goal_change ADD CONSTRAINT fk_cm_user_goal_change_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_session ADD CONSTRAINT fk_cm_learning_session_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_session ADD CONSTRAINT fk_cm_learning_session_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_session ADD CONSTRAINT fk_cm_learning_session_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_session_question ADD CONSTRAINT fk_cm_session_question_session_id FOREIGN KEY (session_id) REFERENCES cm_learning_session(id) ON DELETE RESTRICT;
ALTER TABLE cm_session_question ADD CONSTRAINT fk_cm_session_question_question_id FOREIGN KEY (question_id) REFERENCES cm_question(id) ON DELETE RESTRICT;
ALTER TABLE cm_session_question ADD CONSTRAINT fk_cm_session_question_question_revision_id FOREIGN KEY (question_revision_id) REFERENCES cm_question_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_session_question ADD CONSTRAINT fk_cm_session_question_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_question_attempt ADD CONSTRAINT fk_cm_question_attempt_session_question_id FOREIGN KEY (session_question_id) REFERENCES cm_session_question(id) ON DELETE RESTRICT;
ALTER TABLE cm_attempt_answer ADD CONSTRAINT fk_cm_attempt_answer_attempt_id FOREIGN KEY (attempt_id) REFERENCES cm_question_attempt(id) ON DELETE RESTRICT;
ALTER TABLE cm_attempt_scoring_point ADD CONSTRAINT fk_cm_attempt_scoring_point_attempt_id FOREIGN KEY (attempt_id) REFERENCES cm_question_attempt(id) ON DELETE RESTRICT;
ALTER TABLE cm_attempt_scoring_point ADD CONSTRAINT fk_cm_attempt_scoring_point_scoring_point_id FOREIGN KEY (scoring_point_id) REFERENCES cm_question_scoring_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_attempt_scoring_point ADD CONSTRAINT fk_cm_attempt_scoring_point_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_hint_usage ADD CONSTRAINT fk_cm_hint_usage_attempt_id FOREIGN KEY (attempt_id) REFERENCES cm_question_attempt(id) ON DELETE RESTRICT;
ALTER TABLE cm_error_record ADD CONSTRAINT fk_cm_error_record_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_error_record ADD CONSTRAINT fk_cm_error_record_attempt_id FOREIGN KEY (attempt_id) REFERENCES cm_question_attempt(id) ON DELETE RESTRICT;
ALTER TABLE cm_error_record ADD CONSTRAINT fk_cm_error_record_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_error_reason ADD CONSTRAINT fk_cm_error_reason_error_record_id FOREIGN KEY (error_record_id) REFERENCES cm_error_record(id) ON DELETE RESTRICT;
ALTER TABLE cm_error_reason ADD CONSTRAINT fk_cm_error_reason_misconception_id FOREIGN KEY (misconception_id) REFERENCES cm_misconception(id) ON DELETE RESTRICT;
ALTER TABLE cm_correction_record ADD CONSTRAINT fk_cm_correction_record_error_record_id FOREIGN KEY (error_record_id) REFERENCES cm_error_record(id) ON DELETE RESTRICT;
ALTER TABLE cm_correction_record ADD CONSTRAINT fk_cm_correction_record_profile_settlement_id FOREIGN KEY (profile_settlement_id) REFERENCES cm_profile_settlement(id) ON DELETE RESTRICT;
ALTER TABLE cm_verification_record ADD CONSTRAINT fk_cm_verification_record_correction_record_id FOREIGN KEY (correction_record_id) REFERENCES cm_correction_record(id) ON DELETE RESTRICT;
ALTER TABLE cm_verification_record ADD CONSTRAINT fk_cm_verification_record_profile_settlement_id FOREIGN KEY (profile_settlement_id) REFERENCES cm_profile_settlement(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_task ADD CONSTRAINT fk_cm_learning_task_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_task ADD CONSTRAINT fk_cm_learning_task_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_task ADD CONSTRAINT fk_cm_learning_task_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_task_item ADD CONSTRAINT fk_cm_task_item_task_id FOREIGN KEY (task_id) REFERENCES cm_learning_task(id) ON DELETE RESTRICT;
ALTER TABLE cm_task_item ADD CONSTRAINT fk_cm_task_item_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_task_item ADD CONSTRAINT fk_cm_task_item_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_task_reason ADD CONSTRAINT fk_cm_task_reason_task_item_id FOREIGN KEY (task_item_id) REFERENCES cm_task_item(id) ON DELETE RESTRICT;
ALTER TABLE cm_task_attempt ADD CONSTRAINT fk_cm_task_attempt_task_item_id FOREIGN KEY (task_item_id) REFERENCES cm_task_item(id) ON DELETE RESTRICT;
ALTER TABLE cm_task_attempt ADD CONSTRAINT fk_cm_task_attempt_session_id FOREIGN KEY (session_id) REFERENCES cm_learning_session(id) ON DELETE RESTRICT;
ALTER TABLE cm_task_attempt ADD CONSTRAINT fk_cm_task_attempt_attempt_id FOREIGN KEY (attempt_id) REFERENCES cm_question_attempt(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_settlement ADD CONSTRAINT fk_cm_profile_settlement_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_settlement ADD CONSTRAINT fk_cm_profile_settlement_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_settlement ADD CONSTRAINT fk_cm_profile_settlement_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_settlement ADD CONSTRAINT fk_cm_profile_settlement_source_session_id FOREIGN KEY (source_session_id) REFERENCES cm_learning_session(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_settlement ADD CONSTRAINT fk_cm_profile_settlement_source_attempt_id FOREIGN KEY (source_attempt_id) REFERENCES cm_question_attempt(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_settlement ADD CONSTRAINT fk_cm_profile_settlement_source_error_record_id FOREIGN KEY (source_error_record_id) REFERENCES cm_error_record(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_settlement ADD CONSTRAINT fk_cm_profile_settlement_source_verification_record_id FOREIGN KEY (source_verification_record_id) REFERENCES cm_verification_record(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_settlement ADD CONSTRAINT fk_cm_profile_settlement_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_evidence ADD CONSTRAINT fk_cm_learning_evidence_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_evidence ADD CONSTRAINT fk_cm_learning_evidence_session_id FOREIGN KEY (session_id) REFERENCES cm_learning_session(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_evidence ADD CONSTRAINT fk_cm_learning_evidence_attempt_id FOREIGN KEY (attempt_id) REFERENCES cm_question_attempt(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_evidence ADD CONSTRAINT fk_cm_learning_evidence_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_evidence ADD CONSTRAINT fk_cm_learning_evidence_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_evidence ADD CONSTRAINT fk_cm_learning_evidence_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_profile ADD CONSTRAINT fk_cm_knowledge_profile_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_profile ADD CONSTRAINT fk_cm_knowledge_profile_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_profile ADD CONSTRAINT fk_cm_knowledge_profile_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_change ADD CONSTRAINT fk_cm_profile_change_knowledge_profile_id FOREIGN KEY (knowledge_profile_id) REFERENCES cm_knowledge_profile(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_change ADD CONSTRAINT fk_cm_profile_change_subject_profile_id FOREIGN KEY (subject_profile_id) REFERENCES cm_subject_profile(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_change ADD CONSTRAINT fk_cm_profile_change_overall_profile_id FOREIGN KEY (overall_profile_id) REFERENCES cm_overall_profile(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_change ADD CONSTRAINT fk_cm_profile_change_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_subject_profile ADD CONSTRAINT fk_cm_subject_profile_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_subject_profile ADD CONSTRAINT fk_cm_subject_profile_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_subject_profile ADD CONSTRAINT fk_cm_subject_profile_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_overall_profile ADD CONSTRAINT fk_cm_overall_profile_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_overall_profile ADD CONSTRAINT fk_cm_overall_profile_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_evidence_event ADD CONSTRAINT fk_cm_learning_evidence_event_evidence_id FOREIGN KEY (evidence_id) REFERENCES cm_learning_evidence(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_evidence_event ADD CONSTRAINT fk_cm_learning_evidence_event_replacement_evidence_id FOREIGN KEY (replacement_evidence_id) REFERENCES cm_learning_evidence(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_recalculation_job ADD CONSTRAINT fk_cm_profile_recalculation_job_old_rule_version_id FOREIGN KEY (old_rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_recalculation_job ADD CONSTRAINT fk_cm_profile_recalculation_job_new_rule_version_id FOREIGN KEY (new_rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_checkpoint ADD CONSTRAINT fk_cm_profile_checkpoint_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_checkpoint ADD CONSTRAINT fk_cm_profile_checkpoint_knowledge_point_id FOREIGN KEY (knowledge_point_id) REFERENCES cm_knowledge_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_profile_checkpoint ADD CONSTRAINT fk_cm_profile_checkpoint_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_exam_schedule ADD CONSTRAINT fk_cm_exam_schedule_certification_id FOREIGN KEY (certification_id) REFERENCES cm_exam_certification(id) ON DELETE RESTRICT;
ALTER TABLE cm_exam_schedule_session ADD CONSTRAINT fk_cm_exam_schedule_session_exam_schedule_id FOREIGN KEY (exam_schedule_id) REFERENCES cm_exam_schedule(id) ON DELETE RESTRICT;
ALTER TABLE cm_exam_schedule_session ADD CONSTRAINT fk_cm_exam_schedule_session_exam_subject_id FOREIGN KEY (exam_subject_id) REFERENCES cm_exam_subject(id) ON DELETE RESTRICT;
ALTER TABLE cm_collection ADD CONSTRAINT fk_cm_collection_certification_id FOREIGN KEY (certification_id) REFERENCES cm_exam_certification(id) ON DELETE RESTRICT;
ALTER TABLE cm_collection ADD CONSTRAINT fk_cm_collection_syllabus_version_id FOREIGN KEY (syllabus_version_id) REFERENCES cm_syllabus_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_collection_revision ADD CONSTRAINT fk_cm_collection_revision_collection_id FOREIGN KEY (collection_id) REFERENCES cm_collection(id) ON DELETE RESTRICT;
ALTER TABLE cm_collection_item ADD CONSTRAINT fk_cm_collection_item_collection_revision_id FOREIGN KEY (collection_revision_id) REFERENCES cm_collection_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_collection_item ADD CONSTRAINT fk_cm_collection_item_question_revision_id FOREIGN KEY (question_revision_id) REFERENCES cm_question_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_collection_current ADD CONSTRAINT fk_cm_collection_current_collection_id FOREIGN KEY (collection_id) REFERENCES cm_collection(id) ON DELETE RESTRICT;
ALTER TABLE cm_collection_current ADD CONSTRAINT fk_cm_collection_current_collection_revision_id FOREIGN KEY (collection_revision_id) REFERENCES cm_collection_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_issue ADD CONSTRAINT fk_cm_import_issue_import_batch_id FOREIGN KEY (import_batch_id) REFERENCES cm_import_batch(id) ON DELETE RESTRICT;
ALTER TABLE cm_import_issue ADD CONSTRAINT fk_cm_import_issue_import_record_id FOREIGN KEY (import_record_id) REFERENCES cm_import_record(id) ON DELETE RESTRICT;
ALTER TABLE cm_assessment_report ADD CONSTRAINT fk_cm_assessment_report_session_id FOREIGN KEY (session_id) REFERENCES cm_learning_session(id) ON DELETE RESTRICT;
ALTER TABLE cm_assessment_report ADD CONSTRAINT fk_cm_assessment_report_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_assessment_report ADD CONSTRAINT fk_cm_assessment_report_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_ai_scoring_job ADD CONSTRAINT fk_cm_ai_scoring_job_attempt_id FOREIGN KEY (attempt_id) REFERENCES cm_question_attempt(id) ON DELETE RESTRICT;
ALTER TABLE cm_ai_scoring_job ADD CONSTRAINT fk_cm_ai_scoring_job_question_revision_id FOREIGN KEY (question_revision_id) REFERENCES cm_question_revision(id) ON DELETE RESTRICT;
ALTER TABLE cm_scoring_review ADD CONSTRAINT fk_cm_scoring_review_attempt_scoring_point_id FOREIGN KEY (attempt_scoring_point_id) REFERENCES cm_attempt_scoring_point(id) ON DELETE RESTRICT;
ALTER TABLE cm_daily_task_batch ADD CONSTRAINT fk_cm_daily_task_batch_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_learning_event ADD CONSTRAINT fk_cm_learning_event_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_rule_hit ADD CONSTRAINT fk_cm_rule_hit_rule_version_id FOREIGN KEY (rule_version_id) REFERENCES cm_profile_rule_version(id) ON DELETE RESTRICT;
ALTER TABLE cm_rule_hit ADD CONSTRAINT fk_cm_rule_hit_goal_id FOREIGN KEY (goal_id) REFERENCES cm_user_goal(id) ON DELETE RESTRICT;
ALTER TABLE cm_rule_hit ADD CONSTRAINT fk_cm_rule_hit_session_id FOREIGN KEY (session_id) REFERENCES cm_learning_session(id) ON DELETE RESTRICT;
ALTER TABLE cm_exception_action ADD CONSTRAINT fk_cm_exception_action_exception_event_id FOREIGN KEY (exception_event_id) REFERENCES cm_exception_event(id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_point ADD CONSTRAINT fk_cm_knowledge_point_parent_id_syllabus_version_id_ex_19133673 FOREIGN KEY (parent_id, syllabus_version_id, exam_subject_id) REFERENCES cm_knowledge_point(id, syllabus_version_id, exam_subject_id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT fk_cm_knowledge_prerequisite_knowledge_point_id_syllab_761c6fa3 FOREIGN KEY (knowledge_point_id, syllabus_version_id, exam_subject_id) REFERENCES cm_knowledge_point(id, syllabus_version_id, exam_subject_id) ON DELETE RESTRICT;
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT fk_cm_knowledge_prerequisite_prerequisite_knowledge_po_f7b48e06 FOREIGN KEY (prerequisite_knowledge_point_id, syllabus_version_id, exam_subject_id) REFERENCES cm_knowledge_point(id, syllabus_version_id, exam_subject_id) ON DELETE RESTRICT;
ALTER TABLE cm_question_revision_event ADD CONSTRAINT fk_cm_question_revision_event_question_revision_id_question_id FOREIGN KEY (question_revision_id, question_id) REFERENCES cm_question_revision(id, question_id) ON DELETE RESTRICT;
ALTER TABLE cm_question_knowledge ADD CONSTRAINT fk_cm_question_knowledge_question_revision_id_question_id FOREIGN KEY (question_revision_id, question_id) REFERENCES cm_question_revision(id, question_id) ON DELETE RESTRICT;
ALTER TABLE cm_question_knowledge ADD CONSTRAINT fk_cm_question_knowledge_question_id_exam_subject_id FOREIGN KEY (question_id, exam_subject_id) REFERENCES cm_question(id, exam_subject_id) ON DELETE RESTRICT;
ALTER TABLE cm_question_knowledge ADD CONSTRAINT fk_cm_question_knowledge_knowledge_point_id_exam_subject_id FOREIGN KEY (knowledge_point_id, exam_subject_id) REFERENCES cm_knowledge_point(id, exam_subject_id) ON DELETE RESTRICT;
ALTER TABLE cm_exam_certification ADD CONSTRAINT ck_cm_exam_certification_qualification_level CHECK (qualification_level IN ('HIGH'));
ALTER TABLE cm_question_revision ADD CONSTRAINT ck_cm_question_revision_status CHECK (status IN ('draft', 'pending_review', 'approved', 'rejected', 'published', 'superseded', 'offline'));
ALTER TABLE cm_question_revision ADD CONSTRAINT ck_cm_question_revision_question_type CHECK (question_type IN ('CHOICE', 'CASE', 'ESSAY'));
ALTER TABLE cm_question_revision ADD CONSTRAINT ck_cm_question_revision_knowledge_mapping_status CHECK (knowledge_mapping_status IS NULL OR knowledge_mapping_status IN ('unclassified', 'reviewed'));
ALTER TABLE cm_question_knowledge ADD CONSTRAINT ck_cm_question_knowledge_relation_role CHECK (relation_role IS NULL OR relation_role IN ('primary', 'secondary'));
ALTER TABLE cm_document ADD CONSTRAINT ck_cm_document_document_type CHECK (document_type IN ('syllabus', 'textbook', 'notes'));
ALTER TABLE cm_document ADD CONSTRAINT ck_cm_document_status CHECK (status IN ('draft', 'pending_review', 'approved', 'rejected', 'published', 'offline'));
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_import_type CHECK (import_type IN ('question', 'question_knowledge', 'knowledge_point', 'document_chunk'));
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_status CHECK (status IN ('uploaded', 'parsing', 'validating', 'waiting_confirm', 'importing', 'completed', 'partial_failed', 'failed', 'cancelled'));
ALTER TABLE cm_import_record ADD CONSTRAINT ck_cm_import_record_status CHECK (status IN ('pending', 'success', 'skipped', 'failed'));
ALTER TABLE cm_profile_rule_version ADD CONSTRAINT ck_cm_profile_rule_version_status CHECK (status IN ('draft', 'published', 'retired'));
ALTER TABLE cm_user_goal ADD CONSTRAINT ck_cm_user_goal_status CHECK (status IN ('active', 'paused', 'completed', 'cancelled'));
ALTER TABLE cm_learning_session ADD CONSTRAINT ck_cm_learning_session_session_type CHECK (session_type IN ('initial_diagnosis', 'daily_task', 'task_test', 'self_practice', 'simulation', 'correction', 'independent_verification', 'simulation_verification'));
ALTER TABLE cm_learning_session ADD CONSTRAINT ck_cm_learning_session_status CHECK (status IN ('created', 'in_progress', 'submitted', 'settling', 'completed', 'invalid', 'cancelled'));
ALTER TABLE cm_question_attempt ADD CONSTRAINT ck_cm_question_attempt_status CHECK (status IN ('in_progress', 'submitted', 'graded', 'invalid'));
ALTER TABLE cm_question_attempt ADD CONSTRAINT ck_cm_question_attempt_timer_status CHECK (timer_status IN ('valid', 'missing', 'invalid'));
ALTER TABLE cm_attempt_answer ADD CONSTRAINT ck_cm_attempt_answer_grading_status CHECK (grading_status IN ('pending', 'graded', 'invalid'));
ALTER TABLE cm_hint_usage ADD CONSTRAINT ck_cm_hint_usage_hint_type CHECK (hint_type IN ('direction', 'concept', 'step', 'view_answer'));
ALTER TABLE cm_error_record ADD CONSTRAINT ck_cm_error_record_status CHECK (status IN ('unresolved', 'correcting', 'pending_verification', 'resolved', 'closed'));
ALTER TABLE cm_error_reason ADD CONSTRAINT ck_cm_error_reason_reason_type CHECK (reason_type IN ('standard', 'custom'));
ALTER TABLE cm_correction_record ADD CONSTRAINT ck_cm_correction_record_status CHECK (status IN ('submitted', 'success', 'failed', 'invalid'));
ALTER TABLE cm_verification_record ADD CONSTRAINT ck_cm_verification_record_status CHECK (status IN ('pending', 'passed', 'failed', 'invalid'));
ALTER TABLE cm_learning_task ADD CONSTRAINT ck_cm_learning_task_status CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped', 'cancelled', 'replaced'));
ALTER TABLE cm_task_item ADD CONSTRAINT ck_cm_task_item_item_type CHECK (item_type IN ('question', 'resource', 'knowledge', 'action'));
ALTER TABLE cm_task_item ADD CONSTRAINT ck_cm_task_item_status CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped', 'cancelled'));
ALTER TABLE cm_task_attempt ADD CONSTRAINT ck_cm_task_attempt_status CHECK (status IN ('started', 'completed', 'failed', 'cancelled'));
ALTER TABLE cm_profile_settlement ADD CONSTRAINT ck_cm_profile_settlement_settlement_type CHECK (settlement_type IN ('single', 'batch', 'correction', 'verification'));
ALTER TABLE cm_profile_settlement ADD CONSTRAINT ck_cm_profile_settlement_status CHECK (status IN ('collecting', 'settled', 'superseded', 'failed'));
ALTER TABLE cm_learning_evidence ADD CONSTRAINT ck_cm_learning_evidence_direction CHECK (direction IN ('positive', 'negative', 'neutral', 'invalid'));
ALTER TABLE cm_learning_evidence ADD CONSTRAINT ck_cm_learning_evidence_hint_level CHECK (hint_level IN ('none', 'direction', 'concept', 'step', 'view_answer'));
ALTER TABLE cm_learning_evidence ADD CONSTRAINT ck_cm_learning_evidence_timer_status CHECK (timer_status IN ('valid', 'missing', 'invalid'));
ALTER TABLE cm_knowledge_profile ADD CONSTRAINT ck_cm_knowledge_profile_confidence_level CHECK (confidence_level IN ('unassessed', 'low', 'medium', 'high', 'expired'));
ALTER TABLE cm_knowledge_profile ADD CONSTRAINT ck_cm_knowledge_profile_profile_status CHECK (profile_status IN ('unassessed', 'provisional', 'urgent', 'weak', 'learning', 'proficient', 'mastery_candidate', 'mastered', 'needs_retest', 'pending_verification', 'needs_review', 'expired'));
ALTER TABLE cm_knowledge_profile ADD CONSTRAINT ck_cm_knowledge_profile_recent_trend CHECK (recent_trend IN ('rising', 'stable', 'fluctuating', 'declining'));
ALTER TABLE cm_profile_change ADD CONSTRAINT ck_cm_profile_change_profile_level CHECK (profile_level IN ('knowledge', 'subject', 'overall'));
ALTER TABLE cm_profile_change ADD CONSTRAINT ck_cm_profile_change_change_type CHECK (change_type IN ('initialization', 'answer', 'decay', 'aggregation', 'scoring_correction', 'evidence_replacement', 'replay', 'rule_recalculation'));
ALTER TABLE cm_subject_profile ADD CONSTRAINT ck_cm_subject_profile_confidence_level CHECK (confidence_level IN ('unassessed', 'low', 'medium', 'high'));
ALTER TABLE cm_subject_profile ADD CONSTRAINT ck_cm_subject_profile_efficiency_status CHECK (efficiency_status IS NULL OR efficiency_status IN ('provisional', 'fast_skilled', 'fluent', 'normal', 'slow', 'time_risk'));
ALTER TABLE cm_overall_profile ADD CONSTRAINT ck_cm_overall_profile_profile_stage CHECK (profile_stage IN ('initial', 'formal'));
ALTER TABLE cm_overall_profile ADD CONSTRAINT ck_cm_overall_profile_readiness_level CHECK (readiness_level IS NULL OR readiness_level IN ('insufficient', 'borderline', 'likely', 'stable'));
ALTER TABLE cm_learning_evidence_event ADD CONSTRAINT ck_cm_learning_evidence_event_event_type CHECK (event_type IN ('invalidated', 'restored', 'superseded', 'recalculated'));
ALTER TABLE cm_profile_recalculation_job ADD CONSTRAINT ck_cm_profile_recalculation_job_scope_type CHECK (scope_type IN ('evidence', 'knowledge_profile', 'subject_profile', 'overall_profile', 'goal', 'rule_version'));
ALTER TABLE cm_profile_recalculation_job ADD CONSTRAINT ck_cm_profile_recalculation_job_status CHECK (status IN ('queued', 'running', 'completed', 'partial_failed', 'failed', 'cancelled'));
ALTER TABLE cm_exam_schedule ADD CONSTRAINT ck_cm_exam_schedule_status CHECK (status IN ('draft', 'published', 'superseded'));
ALTER TABLE cm_collection ADD CONSTRAINT ck_cm_collection_collection_type CHECK (collection_type IN ('FIRST_DIAGNOSTIC', 'PRACTICE', 'SIMULATION'));
ALTER TABLE cm_collection_revision ADD CONSTRAINT ck_cm_collection_revision_status CHECK (status IN ('draft', 'pending_review', 'approved', 'rejected', 'published', 'superseded', 'offline'));
ALTER TABLE cm_import_issue ADD CONSTRAINT ck_cm_import_issue_severity CHECK (severity IN ('warning', 'error'));
ALTER TABLE cm_import_issue ADD CONSTRAINT ck_cm_import_issue_status CHECK (status IN ('open', 'resolved', 'ignored'));
ALTER TABLE cm_assessment_report ADD CONSTRAINT ck_cm_assessment_report_status CHECK (status IN ('generating', 'available', 'failed'));
ALTER TABLE cm_ai_scoring_job ADD CONSTRAINT ck_cm_ai_scoring_job_status CHECK (status IN ('pending', 'running', 'succeeded', 'low_confidence', 'manual_review', 'failed'));
ALTER TABLE cm_scoring_review ADD CONSTRAINT ck_cm_scoring_review_status CHECK (status IN ('draft', 'submitted', 'superseded'));
ALTER TABLE cm_daily_task_batch ADD CONSTRAINT ck_cm_daily_task_batch_status CHECK (status IN ('generating', 'available', 'failed', 'replaced'));
ALTER TABLE cm_idempotency_record ADD CONSTRAINT ck_cm_idempotency_record_status CHECK (status IN ('processing', 'succeeded', 'failed'));
ALTER TABLE cm_async_job ADD CONSTRAINT ck_cm_async_job_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled'));
ALTER TABLE cm_exception_event ADD CONSTRAINT ck_cm_exception_event_severity CHECK (severity IN ('info', 'warning', 'error', 'critical'));
ALTER TABLE cm_exception_event ADD CONSTRAINT ck_cm_exception_event_status CHECK (status IN ('open', 'processing', 'resolved', 'ignored'));
ALTER TABLE cm_exception_action ADD CONSTRAINT ck_cm_exception_action_result_status CHECK (result_status IN ('succeeded', 'failed'));
ALTER TABLE cm_export_job ADD CONSTRAINT ck_cm_export_job_status CHECK (status IN ('queued', 'running', 'completed', 'failed', 'expired', 'cancelled'));
ALTER TABLE cm_knowledge_point ADD CONSTRAINT ck_cm_knowledge_point_domain_1 CHECK (tree_depth >= 1);
ALTER TABLE cm_knowledge_point ADD CONSTRAINT ck_cm_knowledge_point_domain_2 CHECK (parent_id IS NULL OR parent_id <> id);
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT ck_cm_knowledge_prerequisite_domain_1 CHECK (knowledge_point_id <> prerequisite_knowledge_point_id);
ALTER TABLE cm_knowledge_prerequisite ADD CONSTRAINT ck_cm_knowledge_prerequisite_domain_2 CHECK (weight IS NULL OR (weight >= 0 AND weight <= 1));
ALTER TABLE cm_question ADD CONSTRAINT ck_cm_question_domain_1 CHECK (question_code ~ '^Q[0-9]{19}$');
ALTER TABLE cm_question_revision ADD CONSTRAINT ck_cm_question_revision_domain_1 CHECK (estimated_seconds IS NULL OR estimated_seconds > 0);
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_domain_1 CHECK (progress_percent BETWEEN 0 AND 100);
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_domain_2 CHECK (valid_count >= 0 AND warning_count >= 0 AND failed_count >= 0 AND generated_count >= 0);
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_domain_3 CHECK ((confirmed_by IS NULL) = (confirmed_time IS NULL));
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_retry_self CHECK (retry_from_batch_id IS NULL OR retry_from_batch_id <> id);
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_file_size CHECK (source_file_size BETWEEN 1 AND 67108864);
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_context CHECK (
    (import_type = 'question' AND syllabus_version_id IS NOT NULL AND exam_subject_id IS NULL AND document_id IS NULL)
    OR (import_type = 'knowledge_point' AND syllabus_version_id IS NOT NULL AND document_id IS NULL AND exam_subject_id IS NULL)
    OR (import_type = 'question_knowledge' AND syllabus_version_id IS NOT NULL AND document_id IS NULL)
    OR (import_type = 'document_chunk' AND document_id IS NOT NULL AND syllabus_version_id IS NULL AND exam_subject_id IS NULL)
);
ALTER TABLE cm_import_record ADD CONSTRAINT ck_cm_import_record_source_line_no CHECK (source_line_no >= 1);
ALTER TABLE cm_error_reason ADD CONSTRAINT ck_cm_error_reason_domain_1 CHECK ((reason_type='standard' AND misconception_id IS NOT NULL AND custom_reason IS NULL) OR (reason_type='custom' AND misconception_id IS NULL AND custom_reason IS NOT NULL));
ALTER TABLE cm_profile_change ADD CONSTRAINT ck_cm_profile_change_domain_1 CHECK ((profile_level='knowledge' AND knowledge_profile_id IS NOT NULL AND subject_profile_id IS NULL AND overall_profile_id IS NULL) OR (profile_level='subject' AND knowledge_profile_id IS NULL AND subject_profile_id IS NOT NULL AND overall_profile_id IS NULL) OR (profile_level='overall' AND knowledge_profile_id IS NULL AND subject_profile_id IS NULL AND overall_profile_id IS NOT NULL));
ALTER TABLE cm_exam_schedule ADD CONSTRAINT ck_cm_exam_schedule_domain_1 CHECK (registration_start IS NULL OR registration_end IS NULL OR registration_end > registration_start);
ALTER TABLE cm_exam_schedule_session ADD CONSTRAINT ck_cm_exam_schedule_session_domain_1 CHECK (end_time > start_time);
ALTER TABLE cm_async_job ADD CONSTRAINT ck_cm_async_job_domain_1 CHECK (attempt_count <= max_attempts);
ALTER TABLE cm_exception_event ADD CONSTRAINT ck_cm_exception_event_domain_1 CHECK (last_occurred_time >= first_occurred_time);
ALTER TABLE cm_question_revision ADD CONSTRAINT ck_cm_question_revision_answer_schema CHECK (answer IS NULL OR (jsonb_typeof(answer) = 'object' AND answer ? 'schema_version'));
ALTER TABLE cm_question_revision_event ADD CONSTRAINT ck_cm_question_revision_event_rejected_fields_schema CHECK (rejected_fields IS NULL OR (jsonb_typeof(rejected_fields) = 'object' AND rejected_fields ? 'schema_version'));
ALTER TABLE cm_document_chunk ADD CONSTRAINT ck_cm_document_chunk_heading_path_schema CHECK (jsonb_typeof(heading_path) = 'object' AND heading_path ? 'schema_version');
ALTER TABLE cm_document_chunk ADD CONSTRAINT ck_cm_document_chunk_source_locator_schema CHECK (jsonb_typeof(source_locator) = 'object' AND source_locator ? 'schema_version');
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_parse_config_schema CHECK (parse_config IS NULL OR (jsonb_typeof(parse_config) = 'object' AND parse_config ? 'schema_version'));
ALTER TABLE cm_import_batch ADD CONSTRAINT ck_cm_import_batch_knowledge_point_parse_config CHECK (
    import_type <> 'knowledge_point'
    OR CASE
        WHEN parse_config IS NOT NULL
         AND jsonb_typeof(parse_config) = 'object'
         AND jsonb_typeof(parse_config -> 'subject_mappings') = 'array'
        THEN parse_config ->> 'schema_version' = 'import_parse_config/1.0'
         AND jsonb_array_length(parse_config -> 'subject_mappings') BETWEEN 1 AND 3
        ELSE false
    END
);
ALTER TABLE cm_import_record ADD CONSTRAINT ck_cm_import_record_raw_record_schema CHECK (jsonb_typeof(raw_record) = 'object' AND raw_record ? 'schema_version');
ALTER TABLE cm_import_record ADD CONSTRAINT ck_cm_import_record_result_data_schema CHECK (result_data IS NULL OR (jsonb_typeof(result_data) = 'object' AND result_data ? 'schema_version'));
ALTER TABLE cm_profile_rule_version ADD CONSTRAINT ck_cm_profile_rule_version_config_data_schema CHECK (jsonb_typeof(config_data) = 'object' AND config_data ? 'schema_version');
ALTER TABLE cm_user_goal_change ADD CONSTRAINT ck_cm_user_goal_change_before_data_schema CHECK (before_data IS NULL OR (jsonb_typeof(before_data) = 'object' AND before_data ? 'schema_version'));
ALTER TABLE cm_user_goal_change ADD CONSTRAINT ck_cm_user_goal_change_after_data_schema CHECK (jsonb_typeof(after_data) = 'object' AND after_data ? 'schema_version');
ALTER TABLE cm_session_question ADD CONSTRAINT ck_cm_session_question_presentation_snapshot_schema CHECK (jsonb_typeof(presentation_snapshot) = 'object' AND presentation_snapshot ? 'schema_version');
ALTER TABLE cm_session_question ADD CONSTRAINT ck_cm_session_question_grading_snapshot_schema CHECK (jsonb_typeof(grading_snapshot) = 'object' AND grading_snapshot ? 'schema_version');
ALTER TABLE cm_session_question ADD CONSTRAINT ck_cm_session_question_knowledge_snapshot_schema CHECK (jsonb_typeof(knowledge_snapshot) = 'object' AND knowledge_snapshot ? 'schema_version');
ALTER TABLE cm_session_question ADD CONSTRAINT ck_cm_session_question_scoring_point_snapshot_schema CHECK (jsonb_typeof(scoring_point_snapshot) = 'object' AND scoring_point_snapshot ? 'schema_version');
ALTER TABLE cm_attempt_answer ADD CONSTRAINT ck_cm_attempt_answer_answer_data_schema CHECK (jsonb_typeof(answer_data) = 'object' AND answer_data ? 'schema_version');
ALTER TABLE cm_learning_task ADD CONSTRAINT ck_cm_learning_task_completion_rule_schema CHECK (jsonb_typeof(completion_rule) = 'object' AND completion_rule ? 'schema_version');
ALTER TABLE cm_learning_task ADD CONSTRAINT ck_cm_learning_task_profile_snapshot_schema CHECK (jsonb_typeof(profile_snapshot) = 'object' AND profile_snapshot ? 'schema_version');
ALTER TABLE cm_task_item ADD CONSTRAINT ck_cm_task_item_target_data_schema CHECK (jsonb_typeof(target_data) = 'object' AND target_data ? 'schema_version');
ALTER TABLE cm_task_reason ADD CONSTRAINT ck_cm_task_reason_evidence_data_schema CHECK (evidence_data IS NULL OR (jsonb_typeof(evidence_data) = 'object' AND evidence_data ? 'schema_version'));
ALTER TABLE cm_profile_settlement ADD CONSTRAINT ck_cm_profile_settlement_settlement_snapshot_schema CHECK (jsonb_typeof(settlement_snapshot) = 'object' AND settlement_snapshot ? 'schema_version');
ALTER TABLE cm_learning_evidence ADD CONSTRAINT ck_cm_learning_evidence_scoring_point_snapshot_schema CHECK (jsonb_typeof(scoring_point_snapshot) = 'object' AND scoring_point_snapshot ? 'schema_version');
ALTER TABLE cm_profile_change ADD CONSTRAINT ck_cm_profile_change_before_data_schema CHECK (before_data IS NULL OR (jsonb_typeof(before_data) = 'object' AND before_data ? 'schema_version'));
ALTER TABLE cm_profile_change ADD CONSTRAINT ck_cm_profile_change_after_data_schema CHECK (jsonb_typeof(after_data) = 'object' AND after_data ? 'schema_version');
ALTER TABLE cm_overall_profile ADD CONSTRAINT ck_cm_overall_profile_subject_snapshot_schema CHECK (jsonb_typeof(subject_snapshot) = 'object' AND subject_snapshot ? 'schema_version');
ALTER TABLE cm_overall_profile ADD CONSTRAINT ck_cm_overall_profile_gate_check_data_schema CHECK (jsonb_typeof(gate_check_data) = 'object' AND gate_check_data ? 'schema_version');
ALTER TABLE cm_profile_recalculation_job ADD CONSTRAINT ck_cm_profile_recalculation_job_scope_data_schema CHECK (jsonb_typeof(scope_data) = 'object' AND scope_data ? 'schema_version');
ALTER TABLE cm_profile_recalculation_job ADD CONSTRAINT ck_cm_profile_recalculation_job_result_summary_schema CHECK (result_summary IS NULL OR (jsonb_typeof(result_summary) = 'object' AND result_summary ? 'schema_version'));
ALTER TABLE cm_profile_recalculation_job ADD CONSTRAINT ck_cm_profile_recalculation_job_failure_objects_schema CHECK (failure_objects IS NULL OR (jsonb_typeof(failure_objects) = 'object' AND failure_objects ? 'schema_version'));
ALTER TABLE cm_profile_checkpoint ADD CONSTRAINT ck_cm_profile_checkpoint_checkpoint_data_schema CHECK (jsonb_typeof(checkpoint_data) = 'object' AND checkpoint_data ? 'schema_version');
ALTER TABLE cm_collection_item ADD CONSTRAINT ck_cm_collection_item_answer_schema_schema CHECK (jsonb_typeof(answer_schema) = 'object' AND answer_schema ? 'schema_version');
ALTER TABLE cm_assessment_report ADD CONSTRAINT ck_cm_assessment_report_subject_scores_schema CHECK (jsonb_typeof(subject_scores) = 'object' AND subject_scores ? 'schema_version');
ALTER TABLE cm_assessment_report ADD CONSTRAINT ck_cm_assessment_report_profile_summary_schema CHECK (jsonb_typeof(profile_summary) = 'object' AND profile_summary ? 'schema_version');
ALTER TABLE cm_ai_scoring_job ADD CONSTRAINT ck_cm_ai_scoring_job_model_config_schema CHECK (jsonb_typeof(model_config) = 'object' AND model_config ? 'schema_version');
ALTER TABLE cm_ai_scoring_job ADD CONSTRAINT ck_cm_ai_scoring_job_input_snapshot_schema CHECK (jsonb_typeof(input_snapshot) = 'object' AND input_snapshot ? 'schema_version');
ALTER TABLE cm_ai_scoring_job ADD CONSTRAINT ck_cm_ai_scoring_job_output_snapshot_schema CHECK (output_snapshot IS NULL OR (jsonb_typeof(output_snapshot) = 'object' AND output_snapshot ? 'schema_version'));
ALTER TABLE cm_daily_task_batch ADD CONSTRAINT ck_cm_daily_task_batch_generation_summary_schema CHECK (jsonb_typeof(generation_summary) = 'object' AND generation_summary ? 'schema_version');
ALTER TABLE cm_idempotency_record ADD CONSTRAINT ck_cm_idempotency_record_response_body_schema CHECK (response_body IS NULL OR (jsonb_typeof(response_body) = 'object' AND response_body ? 'schema_version'));
ALTER TABLE cm_async_job ADD CONSTRAINT ck_cm_async_job_payload_schema CHECK (jsonb_typeof(payload) = 'object' AND payload ? 'schema_version');
ALTER TABLE cm_learning_event ADD CONSTRAINT ck_cm_learning_event_event_data_schema CHECK (jsonb_typeof(event_data) = 'object' AND event_data ? 'schema_version');
ALTER TABLE cm_business_audit_log ADD CONSTRAINT ck_cm_business_audit_log_before_data_schema CHECK (before_data IS NULL OR (jsonb_typeof(before_data) = 'object' AND before_data ? 'schema_version'));
ALTER TABLE cm_business_audit_log ADD CONSTRAINT ck_cm_business_audit_log_after_data_schema CHECK (after_data IS NULL OR (jsonb_typeof(after_data) = 'object' AND after_data ? 'schema_version'));
ALTER TABLE cm_rule_hit ADD CONSTRAINT ck_cm_rule_hit_input_snapshot_schema CHECK (jsonb_typeof(input_snapshot) = 'object' AND input_snapshot ? 'schema_version');
ALTER TABLE cm_rule_hit ADD CONSTRAINT ck_cm_rule_hit_output_snapshot_schema CHECK (jsonb_typeof(output_snapshot) = 'object' AND output_snapshot ? 'schema_version');
ALTER TABLE cm_exception_event ADD CONSTRAINT ck_cm_exception_event_detail_data_schema CHECK (jsonb_typeof(detail_data) = 'object' AND detail_data ? 'schema_version');
ALTER TABLE cm_exception_action ADD CONSTRAINT ck_cm_exception_action_result_data_schema CHECK (jsonb_typeof(result_data) = 'object' AND result_data ? 'schema_version');
ALTER TABLE cm_export_job ADD CONSTRAINT ck_cm_export_job_filter_data_schema CHECK (jsonb_typeof(filter_data) = 'object' AND filter_data ? 'schema_version');
ALTER TABLE cm_export_job ADD CONSTRAINT ck_cm_export_job_desensitisation_schema_schema CHECK (jsonb_typeof(desensitisation_schema) = 'object' AND desensitisation_schema ? 'schema_version');
CREATE UNIQUE INDEX uk_cm_knowledge_point_active_number ON cm_knowledge_point(syllabus_version_id, exam_subject_id, syllabus_number) WHERE del_flag='0';
CREATE UNIQUE INDEX uk_cm_question_revision_working ON cm_question_revision(question_id) WHERE status IN ('draft','pending_review','approved','rejected');
CREATE UNIQUE INDEX uk_cm_question_revision_published ON cm_question_revision(question_id) WHERE status='published';
CREATE UNIQUE INDEX uk_cm_profile_rule_version_published ON cm_profile_rule_version(status) WHERE status='published';
CREATE UNIQUE INDEX uk_cm_user_goal_current ON cm_user_goal(user_id) WHERE status IN ('active','paused');
CREATE UNIQUE INDEX uk_cm_error_reason_standard ON cm_error_reason(error_record_id, misconception_id) WHERE misconception_id IS NOT NULL;
CREATE UNIQUE INDEX uk_cm_profile_settlement_batch_revision ON cm_profile_settlement(source_session_id, knowledge_point_id, settlement_revision_no) WHERE settlement_type='batch';
CREATE UNIQUE INDEX uk_cm_profile_settlement_single_revision ON cm_profile_settlement(source_attempt_id, knowledge_point_id, scoring_revision_no) WHERE settlement_type='single';
CREATE UNIQUE INDEX uk_cm_profile_settlement_correction_revision ON cm_profile_settlement(source_error_record_id, knowledge_point_id, settlement_revision_no) WHERE settlement_type='correction';
CREATE UNIQUE INDEX uk_cm_profile_settlement_verification_revision ON cm_profile_settlement(source_verification_record_id, knowledge_point_id, settlement_revision_no) WHERE settlement_type='verification';
CREATE UNIQUE INDEX uk_cm_learning_evidence_attempt_leaf_current ON cm_learning_evidence(attempt_id, knowledge_point_id) WHERE is_valid=true;
CREATE UNIQUE INDEX uk_cm_learning_evidence_distinct ON cm_learning_evidence(user_id, goal_id, knowledge_point_id, evidence_group_key) WHERE is_valid=true AND is_distinct_question=true;
CREATE UNIQUE INDEX uk_cm_exam_schedule_draft ON cm_exam_schedule(certification_id) WHERE status='draft';
CREATE UNIQUE INDEX uk_cm_exam_schedule_published ON cm_exam_schedule(certification_id) WHERE status='published';
CREATE UNIQUE INDEX uk_cm_collection_revision_working ON cm_collection_revision(collection_id) WHERE status IN ('draft','pending_review','approved','rejected');
CREATE UNIQUE INDEX uk_cm_collection_revision_published ON cm_collection_revision(collection_id) WHERE status='published';
CREATE UNIQUE INDEX uk_cm_import_issue_identity ON cm_import_issue(import_batch_id, COALESCE(import_record_id,0), issue_code, COALESCE(field_path,''));
CREATE UNIQUE INDEX uk_cm_exception_event_open ON cm_exception_event(exception_code,source_type,source_id) WHERE status IN ('open','processing');
CREATE INDEX idx_cm_knowledge_point_parent ON cm_knowledge_point(parent_id);
CREATE INDEX idx_cm_knowledge_point_diagnostic ON cm_knowledge_point(syllabus_version_id,exam_subject_id) WHERE del_flag='0' AND status='0' AND diagnostic_enabled=true;
CREATE INDEX idx_cm_knowledge_point_recommendation ON cm_knowledge_point(syllabus_version_id,exam_subject_id) WHERE del_flag='0' AND status='0' AND recommendation_enabled=true;
CREATE INDEX idx_cm_question_revision_status_update ON cm_question_revision(status,update_time DESC);
CREATE INDEX idx_cm_document_published ON cm_document(syllabus_version_id,update_time DESC) WHERE del_flag='0' AND status='published';
CREATE INDEX idx_cm_import_batch_status_progress ON cm_import_batch(status,started_time DESC);
CREATE INDEX idx_cm_import_record_batch_status ON cm_import_record(batch_id,status);
CREATE INDEX idx_cm_import_record_batch_subject_no ON cm_import_record(batch_id,subject_no);
CREATE INDEX idx_cm_import_issue_batch_severity_id ON cm_import_issue(import_batch_id,severity,id);
CREATE INDEX idx_cm_learning_session_user_status ON cm_learning_session(user_id,status,create_time DESC);
CREATE INDEX idx_cm_question_attempt_user_time ON cm_question_attempt(user_id,submitted_time DESC);
CREATE INDEX idx_cm_error_record_user_status ON cm_error_record(user_id,status,detected_time DESC);
CREATE INDEX idx_cm_learning_task_user_date ON cm_learning_task(user_id,task_date,status);
CREATE INDEX idx_cm_learning_evidence_replay ON cm_learning_evidence(user_id,goal_id,knowledge_point_id,answered_at,attempt_id,id);
CREATE UNIQUE INDEX uk_cm_learning_evidence_sequence ON cm_learning_evidence(user_id,goal_id,knowledge_point_id,settlement_sequence);
CREATE INDEX idx_cm_profile_recalculation_job_status ON cm_profile_recalculation_job(status,create_time);
CREATE INDEX idx_cm_profile_checkpoint_latest ON cm_profile_checkpoint(user_id,goal_id,knowledge_point_id,last_settlement_sequence DESC);
CREATE INDEX idx_cm_ai_scoring_job_queue ON cm_ai_scoring_job(status,create_time);
CREATE INDEX idx_cm_async_job_claim ON cm_async_job(status,next_run_time,id);
CREATE INDEX idx_cm_learning_event_timeline ON cm_learning_event(user_id,goal_id,occurred_time DESC,id DESC);
CREATE INDEX idx_cm_business_audit_timeline ON cm_business_audit_log(domain_code,target_type,target_id,occurred_time DESC);
CREATE INDEX idx_cm_exception_event_queue ON cm_exception_event(status,severity,last_occurred_time DESC);
CREATE INDEX idx_cm_export_job_owner ON cm_export_job(operator_id,create_time DESC);
CREATE INDEX idx_cm_export_job_expiry ON cm_export_job(expires_time) WHERE expires_time IS NOT NULL;
CREATE FUNCTION cm_deny_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME; END $$;
CREATE TRIGGER trg_cm_question_revision_event_append_only BEFORE UPDATE OR DELETE ON cm_question_revision_event FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_user_goal_change_append_only BEFORE UPDATE OR DELETE ON cm_user_goal_change FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_hint_usage_append_only BEFORE UPDATE OR DELETE ON cm_hint_usage FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_profile_change_append_only BEFORE UPDATE OR DELETE ON cm_profile_change FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_learning_evidence_event_append_only BEFORE UPDATE OR DELETE ON cm_learning_evidence_event FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_profile_checkpoint_append_only BEFORE UPDATE OR DELETE ON cm_profile_checkpoint FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_learning_event_append_only BEFORE UPDATE OR DELETE ON cm_learning_event FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_business_audit_log_append_only BEFORE UPDATE OR DELETE ON cm_business_audit_log FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_rule_hit_append_only BEFORE UPDATE OR DELETE ON cm_rule_hit FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE TRIGGER trg_cm_exception_action_append_only BEFORE UPDATE OR DELETE ON cm_exception_action FOR EACH ROW EXECUTE FUNCTION cm_deny_mutation();
CREATE FUNCTION cm_guard_question_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE old_content jsonb; new_content jsonb;
BEGIN
  IF TG_OP='DELETE' AND OLD.status <> 'draft' THEN RAISE EXCEPTION 'non-draft question revision is immutable'; END IF;
  IF TG_OP='UPDATE' AND OLD.status <> 'draft' THEN
    old_content := to_jsonb(OLD) - ARRAY['status','row_version','reviewed_by','reviewed_time','review_opinion','published_by','published_time','update_by','update_time'];
    new_content := to_jsonb(NEW) - ARRAY['status','row_version','reviewed_by','reviewed_time','review_opinion','published_by','published_time','update_by','update_time'];
    IF old_content IS DISTINCT FROM new_content THEN RAISE EXCEPTION 'non-draft question revision content is immutable'; END IF;
  END IF;
  RETURN COALESCE(NEW,OLD);
END $$;
CREATE TRIGGER trg_cm_question_revision_immutable BEFORE UPDATE OR DELETE ON cm_question_revision FOR EACH ROW EXECUTE FUNCTION cm_guard_question_revision();
CREATE FUNCTION cm_guard_status_transition() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE edge text; allowed text[];
BEGIN
  IF NEW.status IS NOT DISTINCT FROM OLD.status THEN RETURN NEW; END IF;
  edge := OLD.status || '>' || NEW.status; allowed := string_to_array(TG_ARGV[0], ',');
  IF NOT edge = ANY(allowed) THEN RAISE EXCEPTION 'illegal status transition on %: %', TG_TABLE_NAME, edge; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_cm_question_revision_status BEFORE UPDATE OF status ON cm_question_revision FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('draft>pending_review,pending_review>approved,pending_review>rejected,approved>published,published>superseded,published>offline');
CREATE TRIGGER trg_cm_document_status BEFORE UPDATE OF status ON cm_document FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('draft>pending_review,pending_review>approved,pending_review>rejected,rejected>draft,approved>published,published>offline');
CREATE TRIGGER trg_cm_import_batch_status BEFORE UPDATE OF status ON cm_import_batch FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('uploaded>parsing,uploaded>cancelled,parsing>validating,parsing>failed,parsing>cancelled,validating>waiting_confirm,validating>failed,validating>cancelled,waiting_confirm>importing,waiting_confirm>cancelled,importing>completed,importing>partial_failed,importing>failed,importing>cancelled');
CREATE TRIGGER trg_cm_profile_rule_version_status BEFORE UPDATE OF status ON cm_profile_rule_version FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('draft>published,published>retired');
CREATE TRIGGER trg_cm_user_goal_status BEFORE UPDATE OF status ON cm_user_goal FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('active>paused,active>completed,active>cancelled,paused>active,paused>completed,paused>cancelled');
CREATE TRIGGER trg_cm_learning_session_status BEFORE UPDATE OF status ON cm_learning_session FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('created>in_progress,created>cancelled,in_progress>submitted,in_progress>invalid,in_progress>cancelled,submitted>settling,submitted>invalid,settling>completed,settling>invalid');
CREATE TRIGGER trg_cm_question_attempt_status BEFORE UPDATE OF status ON cm_question_attempt FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('in_progress>submitted,in_progress>invalid,submitted>graded,submitted>invalid');
CREATE TRIGGER trg_cm_learning_task_status BEFORE UPDATE OF status ON cm_learning_task FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('pending>in_progress,pending>skipped,pending>cancelled,pending>replaced,in_progress>completed,in_progress>skipped,in_progress>cancelled,in_progress>replaced');
CREATE TRIGGER trg_cm_error_record_status BEFORE UPDATE OF status ON cm_error_record FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('unresolved>correcting,unresolved>closed,correcting>pending_verification,correcting>closed,pending_verification>resolved,pending_verification>closed');
CREATE TRIGGER trg_cm_profile_settlement_status BEFORE UPDATE OF status ON cm_profile_settlement FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('collecting>settled,collecting>failed,settled>superseded');
CREATE TRIGGER trg_cm_profile_recalculation_job_status BEFORE UPDATE OF status ON cm_profile_recalculation_job FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('queued>running,queued>cancelled,running>completed,running>partial_failed,running>failed,running>cancelled');
CREATE TRIGGER trg_cm_exam_schedule_status BEFORE UPDATE OF status ON cm_exam_schedule FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('draft>published,published>superseded');
CREATE TRIGGER trg_cm_collection_revision_status BEFORE UPDATE OF status ON cm_collection_revision FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('draft>pending_review,pending_review>approved,pending_review>rejected,approved>published,published>superseded,published>offline');
CREATE TRIGGER trg_cm_ai_scoring_job_status BEFORE UPDATE OF status ON cm_ai_scoring_job FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('pending>running,running>succeeded,running>low_confidence,running>manual_review,running>failed');
CREATE TRIGGER trg_cm_scoring_review_status BEFORE UPDATE OF status ON cm_scoring_review FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('draft>submitted,submitted>superseded');
CREATE TRIGGER trg_cm_async_job_status BEFORE UPDATE OF status ON cm_async_job FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('queued>running,queued>cancelled,running>queued,running>succeeded,running>failed,running>cancelled');
CREATE TRIGGER trg_cm_exception_event_status BEFORE UPDATE OF status ON cm_exception_event FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('open>processing,open>ignored,processing>resolved,processing>ignored');
CREATE TRIGGER trg_cm_export_job_status BEFORE UPDATE OF status ON cm_export_job FOR EACH ROW EXECUTE FUNCTION cm_guard_status_transition('queued>running,queued>cancelled,running>completed,running>failed,running>cancelled,completed>expired');
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='certmuse_app') THEN CREATE ROLE certmuse_app NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA public TO certmuse_app;
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'cm\_%' ESCAPE '\' LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I TO certmuse_app', r.tablename);
  END LOOP;
END $$;
REVOKE UPDATE, DELETE ON cm_question_revision_event FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_user_goal_change FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_hint_usage FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_profile_change FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_learning_evidence_event FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_profile_checkpoint FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_learning_event FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_business_audit_log FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_rule_hit FROM certmuse_app;
REVOKE UPDATE, DELETE ON cm_exception_action FROM certmuse_app;
INSERT INTO cm_exam_certification(id,certification_code,certification_name,qualification_level,status,sort_order)
VALUES (900000000000000001,'SYSTEM_ARCHITECT','系统架构设计师','HIGH','0',1)
ON CONFLICT (certification_code) DO UPDATE SET certification_name=EXCLUDED.certification_name, qualification_level=EXCLUDED.qualification_level;
INSERT INTO cm_exam_subject(id,certification_id,subject_code,subject_name) VALUES
(900000000000000011,900000000000000001,'COMPREHENSIVE','综合知识'),
(900000000000000012,900000000000000001,'CASE_ANALYSIS','案例分析'),
(900000000000000013,900000000000000001,'ESSAY','论文')
ON CONFLICT (certification_id,subject_code) DO UPDATE SET subject_name=EXCLUDED.subject_name;
INSERT INTO cm_syllabus_version(id,certification_id,version_name,published_date)
VALUES (900000000000000021,900000000000000001,'第二版',NULL)
ON CONFLICT (certification_id,version_name) DO NOTHING;
INSERT INTO cm_profile_rule_version(id,version_code,status,config_schema_version,config_data,content_hash,published_time)
VALUES (900000000000000031,'PROFILE_V8','published','profile_rule/1.0','{"aggregation":{"exclude_expired":true,"exclude_unassessed":true,"importance_weights":{"core":3,"normal":2,"supplement":1}},"behavior":{},"confidence":{},"evidence":{"easy":{"correct":70,"wrong":10},"hard":{"correct":95,"wrong":40},"medium":{"correct":85,"wrong":25}},"freshness":{"boundaries_days":[30,60,90],"regression_correct_coefficients":{"days_31_60":1.1,"days_61_90":1.15,"default":1.0,"over_90_days":1.15}},"hint_and_time":{"correct_max":1.21,"grace_ratio":1.2,"hint_levels":{},"standard_seconds":{"easy":20,"hard":60,"medium":40},"time_bands":{"fast":{"correct":1.05,"wrong":1.1},"fluent":{"correct":1.03,"wrong":1.0},"grace":{"correct":0.9,"wrong":1.05},"normal":{"correct":1.0,"wrong":1.0},"timeout":{"wrong":1.1}},"wrong_max":1.6},"readiness":{},"schema_version":"1.0"}'::jsonb,'235c349da5fc6597cc98ed524acd079071562170f497b4136fb9333f72e8c26e',now())
ON CONFLICT (version_code) DO UPDATE SET config_data=EXCLUDED.config_data, content_hash=EXCLUDED.content_hash, update_time=now();
DO $$
DECLARE table_count integer; id_pk_count integer;
BEGIN
 SELECT count(*) INTO table_count FROM information_schema.tables WHERE table_schema='public' AND table_name LIKE 'cm\_%' ESCAPE '\';
 IF table_count <> 66 THEN RAISE EXCEPTION 'expected 66 cm tables, got %',table_count; END IF;
 SELECT count(*) INTO id_pk_count FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON kcu.constraint_name=tc.constraint_name AND kcu.table_schema=tc.table_schema WHERE tc.table_schema='public' AND tc.constraint_type='PRIMARY KEY' AND tc.table_name LIKE 'cm\_%' ESCAPE '\' AND kcu.column_name='id';
 IF id_pk_count <> 65 THEN RAISE EXCEPTION 'expected 65 id primary keys, got %',id_pk_count; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema='public' AND table_name='cm_collection_current' AND constraint_type='PRIMARY KEY') THEN RAISE EXCEPTION 'missing collection current natural primary key'; END IF;
 IF NOT EXISTS (SELECT 1 FROM cm_profile_rule_version WHERE version_code='PROFILE_V8') THEN RAISE EXCEPTION 'missing PROFILE_V8 seed'; END IF;
END $$;
COMMIT;
