package org.dromara.certmuse.catalog.service.impl;

import cn.hutool.core.util.IdUtil;
import cn.hutool.crypto.digest.DigestUtil;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.function.Supplier;
import lombok.RequiredArgsConstructor;
import org.dromara.certmuse.catalog.support.CatalogJsonSchema;
import org.dromara.certmuse.catalog.service.ExamGuidanceService;
import org.dromara.certmuse.catalog.domain.vo.PublicQualificationVo;
import org.dromara.certmuse.shared.schema.VersionedJsonDocumentFactory;
import org.dromara.certmuse.shared.web.CertMuseApiException;
import org.dromara.common.core.domain.PageResult;
import org.dromara.common.satoken.utils.LoginHelper;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

/** PostgreSQL-backed U16 aggregate implementation. */
@Service
@RequiredArgsConstructor
public class ExamGuidanceServiceImpl implements ExamGuidanceService {
    private static final ZoneId SHANGHAI = ZoneId.of("Asia/Shanghai");
    private final JdbcTemplate jdbc;
    private final JsonMapper jsonMapper;

    @Override public Map<String,Object> listPeriods(Integer year, String half, String status, String code, Integer pageNum, Integer pageSize) {
        int size = bounded(pageSize, 20, 1, 100), page = bounded(pageNum, 1, 1, 10000);
        StringBuilder where = new StringBuilder(" where record_origin='official' and status in ('draft','published')"); List<Object> args = new ArrayList<>();
        if (year != null) { where.append(" and exam_year=?"); args.add(year); }
        if (half != null) { where.append(" and half=?"); args.add(half); }
        if (status != null) { where.append(" and status=?"); args.add(status); }
        if (code != null && !code.isBlank()) { where.append(" and period_code=?"); args.add(code.trim()); }
        long total = jdbc.queryForObject("select count(*) from cm_exam_period" + where, Long.class, args.toArray());
        List<Map<String,Object>> rows = jdbc.queryForList("select id::text as \"id\",period_code as \"periodCode\",exam_year as \"examYear\",half,status,revision_no as \"revisionNo\",official_source_url as \"officialSourceUrl\",source_published_at as \"sourcePublishedAt\",row_version as \"rowVersion\",update_time as \"updatedTime\",(select count(*) from cm_exam_schedule s where s.exam_period_id=p.id) as \"scheduleCount\",(select count(*) from cm_exam_region_registration r where r.exam_period_id=p.id) as \"registrationCount\" from cm_exam_period p" + where + " order by exam_year desc,half desc,revision_no desc,id desc limit ? offset ?", with(args,size,(page-1)*size));
        return page(rows,total);
    }
    @Override public Map<String,Object> periodDetail(String id) { return detail(period(number(id))); }
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> createPeriod(String request, JsonNode body) {
        return write("EXAM_GUIDANCE_CREATE_PERIOD",request,body,() -> {
            String code = required(body,"periodCode"); int year = requiredInt(body,"examYear"); String half = required(body,"half");
            if (!code.matches("^[0-9]{4}-H[12]$") || !code.equals(year + "-" + half) || year < LocalDate.now(SHANGHAI).getYear() || year > LocalDate.now(SHANGHAI).getYear()+3) throw invalid("periodCode","期次编码或年份不合法");
            Integer exists = jdbc.queryForObject("select count(*) from cm_exam_period where period_code=?",Integer.class,code); if (exists != null && exists > 0) throw conflict("EXAM_GUIDANCE_DUPLICATE_PERIOD","期次已存在");
            long id=IdUtil.getSnowflakeNextId(); jdbc.update("insert into cm_exam_period(id,period_code,exam_year,half,revision_no,record_origin,status,official_source_url,source_published_at,create_by,update_by) values(?,?,?,?,1,'official','draft',?,?,?,?)",id,code,year,half,https(body,"officialSourceUrl"),sourceTime(body),LoginHelper.getUserId(),LoginHelper.getUserId()); return detail(period(id));
        });
    }
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> updatePeriod(String rawId,String request,JsonNode body) { long id=number(rawId); return write("EXAM_GUIDANCE_UPDATE_PERIOD",request,body,()->{ if(body.has("periodCode")||body.has("examYear")||body.has("half")) throw invalid("periodCode","更新不得修改期次编码、年份或半年度"); Map<String,Object> p=lockPeriod(id); draft(p,body); jdbc.update("update cm_exam_period set official_source_url=?,source_published_at=?,row_version=row_version+1,update_by=?,update_time=now() where id=?",https(body,"officialSourceUrl"),sourceTime(body),LoginHelper.getUserId(),id); return detail(period(id));}); }
    @Override @Transactional(rollbackFor=Exception.class) public void deletePeriod(String rawId,String request,JsonNode body) { long id=number(rawId); write("EXAM_GUIDANCE_DELETE_PERIOD",request,body,()->{Map<String,Object> p=period(id);draft(p,body);jdbc.update("delete from cm_exam_period where id=?",id);return Map.of();}); }
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> createRevision(String rawId,String request,JsonNode body) { long sourceId=number(rawId); return write("EXAM_GUIDANCE_CREATE_REVISION",request,body,()->{Map<String,Object> source=lockPeriod(sourceId); version(source,body); if(!"published".equals(source.get("status"))) throw conflict("EXAM_GUIDANCE_STATE_CONFLICT","仅当前发布期次可复制"); Integer drafts=jdbc.queryForObject("select count(*) from cm_exam_period where period_code=? and status='draft'",Integer.class,source.get("period_code")); if(drafts != null && drafts > 0) throw conflict("EXAM_GUIDANCE_STATE_CONFLICT","当前发布期次已有修订草稿"); long id=IdUtil.getSnowflakeNextId(); int revision=((Number)jdbc.queryForObject("select max(revision_no)+1 from cm_exam_period where period_code=?",Integer.class,source.get("period_code"))).intValue(); jdbc.update("insert into cm_exam_period(id,period_code,exam_year,half,revision_no,supersedes_period_id,record_origin,status,official_source_url,source_published_at,create_by,update_by) select ?,period_code,exam_year,half,?,id,'official','draft',official_source_url,source_published_at,?,? from cm_exam_period where id=?",id,revision,LoginHelper.getUserId(),LoginHelper.getUserId(),sourceId); copyChildren(sourceId,id); return detail(period(id));}); }
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> publish(String rawId,String request,JsonNode body) { long id=number(rawId); return write("EXAM_GUIDANCE_PUBLISH",request,body,()->{Map<String,Object> p=period(id);draft(p,body); Integer schedules=jdbc.queryForObject("select count(*) from cm_exam_schedule where exam_period_id=?",Integer.class,id); Integer sessions=jdbc.queryForObject("select count(*) from cm_exam_schedule_session ss join cm_exam_schedule s on s.id=ss.exam_schedule_id where s.exam_period_id=?",Integer.class,id); Integer registrations=jdbc.queryForObject("select count(*) from cm_exam_region_registration where exam_period_id=?",Integer.class,id); if(schedules==0||sessions==0||registrations==0) throw new CertMuseApiException(422,"EXAM_GUIDANCE_PUBLISH_INCOMPLETE","期次缺少资格、场次或报名信息"); jdbc.update("update cm_exam_period set status='superseded',update_time=now() where period_code=? and status='published'",p.get("period_code")); jdbc.update("update cm_exam_period set status='published',published_by=?,published_time=now(),row_version=row_version+1,update_by=?,update_time=now() where id=?",LoginHelper.getUserId(),LoginHelper.getUserId(),id); Map<String,Object> result=new LinkedHashMap<>();result.put("periodId",String.valueOf(id));result.put("periodCode",p.get("period_code"));result.put("revisionNo",p.get("revision_no"));result.put("status","published");result.put("rowVersion",((Number)p.get("row_version")).longValue()+1);return result;}); }
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> saveSchedule(String periodRaw,String scheduleRaw,String request,JsonNode body) { return write(scheduleRaw==null?"EXAM_GUIDANCE_CREATE_SCHEDULE":"EXAM_GUIDANCE_UPDATE_SCHEDULE",request,body,()->{long scheduleId=scheduleRaw==null?IdUtil.getSnowflakeNextId():number(scheduleRaw); long periodId=scheduleRaw==null?number(periodRaw):((Number)one("select exam_period_id from cm_exam_schedule where id=?",number(scheduleRaw)).get("exam_period_id")).longValue(); Map<String,Object> p=period(periodId);draft(p,body,"expectedPeriodRowVersion"); long certification=number(required(body,"certificationId")); Integer eligible=jdbc.queryForObject("select count(*) from cm_exam_certification where id=? and status='0'",Integer.class,certification);if(eligible==null||eligible==0)throw invalid("certificationId","资格必须为启用状态"); JsonNode sessions=body.path("sessions"); if(!sessions.isArray()||sessions.isEmpty()) throw invalid("sessions","至少需要一个场次"); LocalDate start=null,end=null; for(JsonNode s:sessions){OffsetDateTime a=time(s,"startTime"),b=time(s,"endTime");if(!b.isAfter(a))throw invalid("sessions","结束时间必须晚于开始时间");LocalDate d=a.atZoneSameInstant(SHANGHAI).toLocalDate();if(!((String)p.get("half")).equals(d.getMonthValue()<=6?"H1":"H2"))throw invalid("sessions","场次开始时间不属于期次半年度");start=start==null||d.isBefore(start)?d:start;LocalDate e=b.atZoneSameInstant(SHANGHAI).toLocalDate();end=end==null||e.isAfter(end)?e:end;}
            if(scheduleRaw==null) jdbc.update("insert into cm_exam_schedule(id,certification_id,revision_no,exam_date,exam_period_id,exam_start_date,exam_end_date,public_note,status) values(?,?,1,?,?,?,?,?, 'draft')",scheduleId,certification,start,periodId,start,end,text(body,"publicNote")); else {jdbc.update("delete from cm_exam_schedule_session where exam_schedule_id=?",scheduleId);jdbc.update("update cm_exam_schedule set certification_id=?,exam_date=?,exam_start_date=?,exam_end_date=?,public_note=? where id=?",certification,start,start,end,text(body,"publicNote"),scheduleId);} for(JsonNode s:sessions) jdbc.update("insert into cm_exam_schedule_session(id,exam_schedule_id,exam_subject_id,certification_id,session_code,start_time,end_time,sort_order) values(?,?,?,?,?,?,?,?)",IdUtil.getSnowflakeNextId(),scheduleId,number(required(s,"examSubjectId")),certification,required(s,"sessionCode"),time(s,"startTime"),time(s,"endTime"),s.path("sortOrder").asInt()); bump(periodId);return Map.of("periodId",String.valueOf(periodId),"scheduleId",String.valueOf(scheduleId),"periodRowVersion",versionOf(periodId));}); }
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> deleteSchedule(String raw,String request,JsonNode body){return write("EXAM_GUIDANCE_DELETE_SCHEDULE",request,body,()->{long id=number(raw),periodId=((Number)one("select exam_period_id from cm_exam_schedule where id=?",id).get("exam_period_id")).longValue();draft(period(periodId),body,"expectedPeriodRowVersion");jdbc.update("delete from cm_exam_schedule where id=?",id);bump(periodId);return Map.of("periodId",String.valueOf(periodId),"deletedScheduleId",String.valueOf(id),"periodRowVersion",versionOf(periodId));});}
    @Override public Map<String,Object> listRegions(String keyword,String status,String type,Integer pageNum,Integer pageSize){
        int size=bounded(pageSize,20,1,100),page=bounded(pageNum,1,1,10000);StringBuilder where=new StringBuilder(" where 1=1");List<Object> args=new ArrayList<>();
        if(keyword!=null&&!keyword.isBlank()){String term="%"+keyword.trim()+"%";where.append(" and (region_name ilike ? or region_code ilike ?)");args.add(term);args.add(term);}
        if(status!=null&&!status.isBlank()){where.append(" and status=?");args.add(status);}
        if(type!=null&&!type.isBlank()){where.append(" and region_type=?");args.add(type);}
        long total=jdbc.queryForObject("select count(*) from cm_exam_region"+where,Long.class,args.toArray());
        return page(jdbc.queryForList("select id::text as \"id\",region_code as \"regionCode\",region_name as \"regionName\",region_type as \"regionType\",parent_region_code as \"parentRegionCode\",institution_name as \"institutionName\",contact_phone as \"contactPhone\",local_notice_url as \"localNoticeUrl\",sort_order as \"sortOrder\",status,row_version as \"rowVersion\",update_time as \"updatedTime\" from cm_exam_region"+where+" order by sort_order,id limit ? offset ?",with(args,size,(page-1)*size)),total);
    }
    @Override public Map<String,Object> regionDetail(String raw){return region(number(raw));}
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> updateRegion(String raw,String request,JsonNode body){long id=number(raw);return write("EXAM_GUIDANCE_UPDATE_REGION",request,body,()->{Map<String,Object> r=region(id);regionVersion(r,body);int sort=body.path("sortOrder").asInt(-1);if(sort<0)throw invalid("sortOrder","排序必须为非负整数");String status=required(body,"status");if(!"enabled".equals(status)&&!"disabled".equals(status))throw invalid("status","状态不合法");jdbc.update("update cm_exam_region set institution_name=?,contact_phone=?,local_notice_url=?,sort_order=?,status=?,row_version=row_version+1,update_by=?,update_time=now() where id=?",nullable(text(body,"institutionName")),nullable(text(body,"contactPhone")),notice(body),sort,status,LoginHelper.getUserId(),id);return region(id);});}
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> saveRegistration(String periodRaw,String regRaw,String request,JsonNode body){return write(regRaw==null?"EXAM_GUIDANCE_CREATE_REGISTRATION":"EXAM_GUIDANCE_UPDATE_REGISTRATION",request,body,()->{long id=regRaw==null?IdUtil.getSnowflakeNextId():number(regRaw);long periodId=regRaw==null?number(periodRaw):((Number)one("select exam_period_id from cm_exam_region_registration where id=?",id).get("exam_period_id")).longValue();draft(period(periodId),body,"expectedPeriodRowVersion");OffsetDateTime end=time(body,"registrationEnd"),start=optionalTime(body,"registrationStart");if(start!=null&&!start.isBefore(end))throw invalid("registrationStart","报名开始必须早于截止");OffsetDateTime last=jdbc.queryForObject("select max(ss.end_time) from cm_exam_schedule_session ss join cm_exam_schedule s on s.id=ss.exam_schedule_id where s.exam_period_id=?",OffsetDateTime.class,periodId);if(last!=null&&end.isAfter(last))throw invalid("registrationEnd","报名截止不得晚于最后考试时间");if(regRaw==null)jdbc.update("insert into cm_exam_region_registration(id,exam_period_id,region_id,registration_start,registration_end,review_start,review_end,payment_start,payment_end,qualification_review_note,payment_note,official_source_url,source_published_at,create_by,update_by) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,periodId,number(required(body,"regionId")),start,end,optionalTime(body,"reviewStart"),optionalTime(body,"reviewEnd"),optionalTime(body,"paymentStart"),optionalTime(body,"paymentEnd"),text(body,"qualificationReviewNote"),text(body,"paymentNote"),https(body,"officialSourceUrl"),sourceTime(body),LoginHelper.getUserId(),LoginHelper.getUserId());else jdbc.update("update cm_exam_region_registration set registration_start=?,registration_end=?,review_start=?,review_end=?,payment_start=?,payment_end=?,qualification_review_note=?,payment_note=?,official_source_url=?,source_published_at=?,update_by=?,update_time=now() where id=?",start,end,optionalTime(body,"reviewStart"),optionalTime(body,"reviewEnd"),optionalTime(body,"paymentStart"),optionalTime(body,"paymentEnd"),text(body,"qualificationReviewNote"),text(body,"paymentNote"),https(body,"officialSourceUrl"),sourceTime(body),LoginHelper.getUserId(),id);bump(periodId);return Map.of("periodId",String.valueOf(periodId),"registrationId",String.valueOf(id),"periodRowVersion",versionOf(periodId));});}
    @Override @Transactional(rollbackFor=Exception.class) public Map<String,Object> deleteRegistration(String raw,String request,JsonNode body){return write("EXAM_GUIDANCE_DELETE_REGISTRATION",request,body,()->{long id=number(raw),periodId=((Number)one("select exam_period_id from cm_exam_region_registration where id=?",id).get("exam_period_id")).longValue();draft(period(periodId),body,"expectedPeriodRowVersion");jdbc.update("delete from cm_exam_region_registration where id=?",id);bump(periodId);return Map.of("periodId",String.valueOf(periodId),"deletedRegistrationId",String.valueOf(id),"periodRowVersion",versionOf(periodId));});}
    @Override public Map<String,Object> qualificationContext(Integer year,String half){
        int nowYear=LocalDate.now(SHANGHAI).getYear(); if(half==null||(!"UNKNOWN".equals(half)&&!"H1".equals(half)&&!"H2".equals(half)))throw invalid("targetHalf","目标半年度不合法"); if("UNKNOWN".equals(half)){if(year!=null)throw invalid("targetYear","UNKNOWN 不得传入目标年份");}else if(year==null||year<nowYear||year>nowYear+3)throw invalid("targetYear","目标年份不合法");
        Map<String,Object> period; if("UNKNOWN".equals(half)){List<Map<String,Object>> candidates=jdbc.queryForList("select p.* from cm_exam_period p join cm_exam_schedule s on s.exam_period_id=p.id where p.status='published' and p.record_origin='official' and s.exam_end_date>=current_date group by p.id order by min(s.exam_start_date),p.id limit 1");if(candidates.isEmpty())throw new CertMuseApiException(422,"EXAM_GUIDANCE_NO_FUTURE_PERIOD","没有未来官方考试期次");period=candidates.getFirst();}else{List<Map<String,Object>> candidates=jdbc.queryForList("select * from cm_exam_period where exam_year=? and half=? and status='published' and record_origin='official'",year,half);if(candidates.isEmpty())return context(year,half,null,"PENDING_OFFICIAL",List.of());period=candidates.getFirst();}
        long periodId=((Number)period.get("id")).longValue();List<Map<String,Object>> q=jdbc.queryForList("select s.id as schedule_id,s.certification_id::text as \"certificationId\",c.certification_code as \"certificationCode\",c.certification_name as \"certificationName\",c.qualification_level as level,s.exam_start_date as \"examStartDate\",s.exam_end_date as \"examEndDate\",s.public_note as \"publicNote\" from cm_exam_schedule s join cm_exam_certification c on c.id=s.certification_id where s.exam_period_id=? and c.status='0' and s.exam_end_date>=current_date order by c.sort_order,s.certification_id",periodId);for(Map<String,Object> item:q){long scheduleId=((Number)item.remove("schedule_id")).longValue();item.put("sessions",jdbc.queryForList("select ss.exam_subject_id::text as \"examSubjectId\",es.subject_name as \"subjectName\",ss.session_code as \"sessionCode\",ss.start_time as \"startTime\",ss.end_time as \"endTime\",ss.sort_order as \"sortOrder\" from cm_exam_schedule_session ss join cm_exam_subject es on es.id=ss.exam_subject_id where ss.exam_schedule_id=? order by ss.sort_order",scheduleId));}return context(year,half,(String)period.get("period_code"),q.isEmpty()?"ENDED":"OFFICIAL",q);
    }
    @Override public List<PublicQualificationVo> publicQualifications(){
        LocalDate today = LocalDate.now(SHANGHAI);
        return jdbc.query("select c.certification_code,c.certification_name,c.qualification_level,next_schedule.exam_start_date as nearest_exam_start_date from cm_exam_certification c left join lateral (select s.exam_start_date from cm_exam_schedule s join cm_exam_period p on p.id=s.exam_period_id where s.certification_id=c.id and p.status='published' and p.record_origin='official' and s.exam_start_date>=? order by s.exam_start_date,s.id limit 1) next_schedule on true where c.status='0' order by c.sort_order,c.id",(resultSet,rowNum)->new PublicQualificationVo(resultSet.getString("certification_code"),resultSet.getString("certification_name"),resultSet.getString("qualification_level"),resultSet.getObject("nearest_exam_start_date",LocalDate.class)),today);
    }
    @Override public Map<String,Object> publicRegions(String code){
        List<Map<String,Object>> rows; if(code==null||code.isBlank()){rows=jdbc.queryForList("select region_code as \"regionCode\",region_name as \"regionName\",region_type as \"regionType\",institution_name as \"institutionName\",contact_phone as \"contactPhone\",local_notice_url as \"localNoticeUrl\" from cm_exam_region where status='enabled' order by sort_order,id");for(Map<String,Object> row:rows)row.put("registration",null);return regions(null,rows);} if(!code.matches("^[0-9]{4}-H[12]$"))throw invalid("periodCode","期次编码不合法");List<Map<String,Object>> periods=jdbc.queryForList("select id from cm_exam_period where period_code=? and status='published' and record_origin='official'",code);if(periods.isEmpty())throw new CertMuseApiException(404,"EXAM_GUIDANCE_PERIOD_NOT_PUBLIC","考期未公开");long periodId=((Number)periods.getFirst().get("id")).longValue();rows=jdbc.queryForList("select r.region_code as \"regionCode\",r.region_name as \"regionName\",r.region_type as \"regionType\",r.institution_name as \"institutionName\",r.contact_phone as \"contactPhone\",r.local_notice_url as \"localNoticeUrl\",reg.registration_start as \"registrationStart\",reg.registration_end as \"registrationEnd\",reg.review_start as \"reviewStart\",reg.review_end as \"reviewEnd\",reg.payment_start as \"paymentStart\",reg.payment_end as \"paymentEnd\",reg.qualification_review_note as \"qualificationReviewNote\",reg.payment_note as \"paymentNote\",reg.official_source_url as \"officialSourceUrl\",reg.source_published_at as \"sourcePublishedAt\" from cm_exam_region r left join cm_exam_region_registration reg on reg.region_id=r.id and reg.exam_period_id=? order by r.sort_order,r.id",periodId);for(Map<String,Object> row:rows){Object end=row.remove("registrationEnd");Map<String,Object> registration=new LinkedHashMap<>();if(end==null){registration.put("availability","NOT_PUBLISHED");registration.put("registrationStart",null);registration.put("registrationEnd",null);registration.put("reviewStart",null);registration.put("reviewEnd",null);registration.put("paymentStart",null);registration.put("paymentEnd",null);registration.put("qualificationReviewNote",null);registration.put("paymentNote",null);registration.put("officialSourceUrl",null);registration.put("sourcePublishedAt",null);}else{OffsetDateTime start=(OffsetDateTime)row.remove("registrationStart");OffsetDateTime deadline=(OffsetDateTime)end;OffsetDateTime now=OffsetDateTime.now(SHANGHAI);registration.put("availability",!now.isBefore(deadline)?"CLOSED":start==null?"OPENING_UNKNOWN":now.isBefore(start)?"UPCOMING":"OPEN");registration.put("registrationStart",start);registration.put("registrationEnd",deadline);for(String field:List.of("reviewStart","reviewEnd","paymentStart","paymentEnd","qualificationReviewNote","paymentNote","officialSourceUrl","sourcePublishedAt"))registration.put(field,row.remove(field));}row.put("registration",registration);}return regions(code,rows);
    }
    private Map<String,Object> context(Integer targetYear,String targetHalf,String periodCode,String availability,List<Map<String,Object>> qualifications){Map<String,Object> result=new LinkedHashMap<>();result.put("targetYear",targetYear);result.put("targetHalf",targetHalf);result.put("availability",availability);result.put("periodCode",periodCode);result.put("qualifications",qualifications);return result;} private Map<String,Object> regions(String periodCode,List<Map<String,Object>> values){Map<String,Object> result=new LinkedHashMap<>();result.put("periodCode",periodCode);result.put("regions",values);return result;}
    private Map<String,Object> detail(Map<String,Object> p){long id=((Number)p.get("id")).longValue();Map<String,Object> out=new LinkedHashMap<>();out.put("id",String.valueOf(id));out.put("periodCode",p.get("period_code"));out.put("examYear",p.get("exam_year"));out.put("half",p.get("half"));out.put("status",p.get("status"));out.put("revisionNo",p.get("revision_no"));out.put("supersedesPeriodId",p.get("supersedes_period_id"));out.put("officialSourceUrl",p.get("official_source_url"));out.put("sourcePublishedAt",p.get("source_published_at"));out.put("rowVersion",p.get("row_version"));out.put("createdTime",p.get("create_time"));out.put("updatedTime",p.get("update_time"));out.put("publishedBy",p.get("published_by"));out.put("publishedTime",p.get("published_time"));List<Map<String,Object>> schedules=jdbc.queryForList("select s.id::text as \"id\",s.certification_id::text as \"certificationId\",c.certification_name as \"certificationName\",c.qualification_level as level,s.exam_start_date as \"examStartDate\",s.exam_end_date as \"examEndDate\",s.public_note as \"publicNote\" from cm_exam_schedule s join cm_exam_certification c on c.id=s.certification_id where s.exam_period_id=? order by s.id",id);for(Map<String,Object> s:schedules)s.put("sessions",jdbc.queryForList("select ss.id::text as \"id\",ss.exam_subject_id::text as \"examSubjectId\",subject_name as \"subjectName\",session_code as \"sessionCode\",start_time as \"startTime\",end_time as \"endTime\",sort_order as \"sortOrder\" from cm_exam_schedule_session ss join cm_exam_subject subject on subject.id=ss.exam_subject_id where ss.exam_schedule_id=? order by ss.sort_order",Long.parseLong((String)s.get("id"))));out.put("schedules",schedules);out.put("registrations",jdbc.queryForList("select reg.id::text as \"id\",reg.region_id::text as \"regionId\",r.region_code as \"regionCode\",r.region_name as \"regionName\",reg.registration_start as \"registrationStart\",reg.registration_end as \"registrationEnd\",reg.review_start as \"reviewStart\",reg.review_end as \"reviewEnd\",reg.payment_start as \"paymentStart\",reg.payment_end as \"paymentEnd\",reg.qualification_review_note as \"qualificationReviewNote\",reg.payment_note as \"paymentNote\",reg.official_source_url as \"officialSourceUrl\",reg.source_published_at as \"sourcePublishedAt\" from cm_exam_region_registration reg join cm_exam_region r on r.id=reg.region_id where reg.exam_period_id=? order by r.sort_order",id));return out;}
    private void copyChildren(long sourceId,long targetId){
        for(Map<String,Object> source:jdbc.queryForList("select * from cm_exam_schedule where exam_period_id=? order by id",sourceId)){
            long newId=IdUtil.getSnowflakeNextId(), oldId=((Number)source.get("id")).longValue();
            jdbc.update("insert into cm_exam_schedule(id,certification_id,revision_no,exam_date,exam_period_id,exam_start_date,exam_end_date,public_note,copied_from_id,status) values(?,?,1,?,?,?,?,?,?,'draft')",newId,source.get("certification_id"),source.get("exam_date"),targetId,source.get("exam_start_date"),source.get("exam_end_date"),source.get("public_note"),oldId);
            for(Map<String,Object> session:jdbc.queryForList("select * from cm_exam_schedule_session where exam_schedule_id=? order by id",oldId)) jdbc.update("insert into cm_exam_schedule_session(id,exam_schedule_id,exam_subject_id,certification_id,session_code,start_time,end_time,sort_order) values(?,?,?,?,?,?,?,?)",IdUtil.getSnowflakeNextId(),newId,session.get("exam_subject_id"),session.get("certification_id"),session.get("session_code"),session.get("start_time"),session.get("end_time"),session.get("sort_order"));
        }
        for(Map<String,Object> reg:jdbc.queryForList("select * from cm_exam_region_registration where exam_period_id=? order by id",sourceId)) jdbc.update("insert into cm_exam_region_registration(id,exam_period_id,region_id,registration_start,registration_end,review_start,review_end,payment_start,payment_end,qualification_review_note,payment_note,official_source_url,source_published_at,copied_from_id,create_by,update_by) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",IdUtil.getSnowflakeNextId(),targetId,reg.get("region_id"),reg.get("registration_start"),reg.get("registration_end"),reg.get("review_start"),reg.get("review_end"),reg.get("payment_start"),reg.get("payment_end"),reg.get("qualification_review_note"),reg.get("payment_note"),reg.get("official_source_url"),reg.get("source_published_at"),reg.get("id"),LoginHelper.getUserId(),LoginHelper.getUserId());
    }
    private Map<String,Object> period(long id){return one("select * from cm_exam_period where id=?",id);} private Map<String,Object> lockPeriod(long id){return one("select * from cm_exam_period where id=? for update",id);} private Map<String,Object> region(long id){return one("select id,region_code as \"regionCode\",region_name as \"regionName\",region_type as \"regionType\",parent_region_code as \"parentRegionCode\",institution_name as \"institutionName\",contact_phone as \"contactPhone\",local_notice_url as \"localNoticeUrl\",sort_order as \"sortOrder\",status,row_version as \"rowVersion\",update_time as \"updatedTime\" from cm_exam_region where id=?",id);} private Map<String,Object> one(String sql,Object... args){try{return jdbc.queryForMap(sql,args);}catch(EmptyResultDataAccessException e){throw new CertMuseApiException(404,"EXAM_GUIDANCE_RESOURCE_NOT_FOUND","资源不存在");}}
    private Map<String, Object> write(String action, String request, JsonNode body, Supplier<Map<String, Object>> work) {
        String key = requestId(request);
        String hash = DigestUtil.sha256Hex(body.toString());
        List<Map<String, Object>> existing = jdbc.queryForList(
            "select payload_hash,status,response_body from cm_idempotency_record where action_code=? and request_id=?", action, key);
        if (!existing.isEmpty()) {
            Map<String, Object> record = existing.getFirst();
            if (!hash.equals(record.get("payload_hash"))) throw conflict("EXAM_GUIDANCE_IDEMPOTENCY_CONFLICT", "请求号载荷不一致");
            if ("processing".equals(record.get("status"))) {
                throw new CertMuseApiException(409, "EXAM_GUIDANCE_REQUEST_IN_PROGRESS", "请求处理中", true, null, List.of(), null, null);
            }
            try {
                return jsonMapper.treeToValue(jsonMapper.readTree((String) record.get("response_body")).path("response").path("data"), Map.class);
            } catch (Exception exception) {
                throw new CertMuseApiException(500, "EXAM_GUIDANCE_SYSTEM_FAILURE", "读取幂等响应失败");
            }
        }
        jdbc.update("insert into cm_idempotency_record(id,action_code,request_id,payload_hash,status,resource_type,expires_time) values(?,?,?,?, 'processing','exam_guidance',now()+interval '24 hours')",
            IdUtil.getSnowflakeNextId(), action, key, hash);
        Map<String, Object> result = work.get();
        try {
            String envelope = VersionedJsonDocumentFactory.json(jsonMapper, CatalogJsonSchema.EXAM_GUIDANCE_IDEMPOTENCY,
                Map.of("response", Map.of("data", result)));
            jdbc.update("update cm_idempotency_record set status='succeeded',response_status=200,response_body=cast(? as jsonb),update_time=now() where action_code=? and request_id=?",
                envelope, action, key);
        } catch (Exception exception) {
            throw new CertMuseApiException(500, "EXAM_GUIDANCE_SYSTEM_FAILURE", "保存幂等响应失败");
        }
        return result;
    }
    private void draft(Map<String,Object> p,JsonNode body){draft(p,body,"expectedRowVersion");} private void draft(Map<String,Object> p,JsonNode b,String field){if(!"draft".equals(p.get("status")))throw conflict("EXAM_GUIDANCE_STATE_CONFLICT","仅草稿可写");version(p,b,field);} private void version(Map<String,Object> p,JsonNode b){version(p,b,"expectedRowVersion");} private void version(Map<String,Object> p,JsonNode b,String f){if(!b.has(f)||b.path(f).asLong(-1)!=((Number)p.get("row_version")).longValue())throw conflict("expectedRowVersion".equals(f)?"EXAM_GUIDANCE_ROW_VERSION_CONFLICT":"EXAM_GUIDANCE_PERIOD_VERSION_CONFLICT","版本已变化");} private void regionVersion(Map<String,Object> r,JsonNode b){if(!b.has("expectedRowVersion")||b.path("expectedRowVersion").asLong(-1)!=((Number)r.get("rowVersion")).longValue())throw conflict("EXAM_GUIDANCE_ROW_VERSION_CONFLICT","版本已变化");}
    private void bump(long id){jdbc.update("update cm_exam_period set row_version=row_version+1,update_time=now() where id=?",id);} private long versionOf(long id){return ((Number)period(id).get("row_version")).longValue();} private int bounded(Integer n,int def,int min,int max){int x=n==null?def:n;if(x<min||x>max)throw invalid("page","分页参数不合法");return x;} private long number(String v){try{return Long.parseLong(v);}catch(Exception e){throw invalid("id","ID不合法");}} private String requestId(String v){try{return UUID.fromString(v).toString().toLowerCase(Locale.ROOT);}catch(Exception e){throw invalid("X-Request-Id","请求号必须是UUID");}} private String required(JsonNode n,String f){String v=text(n,f);if(v==null||v.isBlank())throw invalid(f,"字段不能为空");return v.trim();} private int requiredInt(JsonNode n,String f){if(!n.has(f)||!n.path(f).canConvertToInt())throw invalid(f,"字段必须是整数");return n.path(f).asInt();} private String text(JsonNode n,String f){return n.hasNonNull(f)?n.path(f).asText():null;} private Object nullable(String v){return v==null||v.isBlank()?null:v.trim();} private OffsetDateTime time(JsonNode n,String f){try{return OffsetDateTime.parse(required(n,f));}catch(Exception e){throw invalid(f,"时间格式不合法");}} private OffsetDateTime sourceTime(JsonNode n){OffsetDateTime value=time(n,"sourcePublishedAt");if(value.isAfter(OffsetDateTime.now(SHANGHAI).plusMinutes(5)))throw invalid("sourcePublishedAt","来源发布时间不能晚于当前时间五分钟");return value;} private OffsetDateTime optionalTime(JsonNode n,String f){String v=text(n,f);return v==null||v.isBlank()?null:time(n,f);} private String https(JsonNode n,String f){String v=required(n,f);if(!v.matches("^https://[^#\\s]{1,2040}$"))throw invalid(f,"必须为无片段HTTPS地址");return v;} private String notice(JsonNode n){String v=required(n,"localNoticeUrl");if(!v.matches("^https?://[^#\\s]{1,2040}$"))throw invalid("localNoticeUrl","地址不合法");return v;} private CertMuseApiException invalid(String f,String m){return new CertMuseApiException(400,"EXAM_GUIDANCE_REQUEST_INVALID",m);} private CertMuseApiException conflict(String c,String m){return new CertMuseApiException(409,c,m);} private Map<String,Object> page(List<Map<String,Object>> rows,long total){Map<String,Object> out=new LinkedHashMap<>();out.put("rows",rows);out.put("total",total);return out;} private Object[] with(List<Object> values,Object... tail){List<Object> all=new ArrayList<>(values);for(Object x:tail)all.add(x);return all.toArray();}
}
