-- Local demonstration schema. It is intentionally separate from production
-- migrations and contains no imported user, customer, or examination data.

CREATE TABLE sys_user (
    user_id bigint PRIMARY KEY,
    dept_id bigint,
    user_name varchar(64) NOT NULL UNIQUE,
    nick_name varchar(64) NOT NULL,
    user_type varchar(32) NOT NULL DEFAULT 'sys_user',
    email varchar(128),
    phone_number varchar(32),
    gender char(1) NOT NULL DEFAULT '2',
    avatar bigint,
    password varchar(128) NOT NULL,
    status char(1) NOT NULL DEFAULT '0',
    del_flag char(1) NOT NULL DEFAULT '0',
    login_ip varchar(128),
    login_date timestamp,
    first_login_at timestamp,
    remark varchar(500),
    create_dept bigint,
    create_by bigint,
    create_time timestamp NOT NULL DEFAULT now(),
    update_by bigint,
    update_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE sys_client (
    id bigint PRIMARY KEY,
    client_id varchar(128) NOT NULL UNIQUE,
    client_key varchar(128) NOT NULL,
    client_secret varchar(128) NOT NULL,
    grant_type varchar(256) NOT NULL,
    device_type varchar(32) NOT NULL,
    access_path varchar(1024),
    ip_whitelist varchar(1024),
    active_timeout bigint NOT NULL,
    timeout bigint NOT NULL,
    status char(1) NOT NULL DEFAULT '0',
    del_flag char(1) NOT NULL DEFAULT '0',
    create_dept bigint,
    create_by bigint,
    create_time timestamp NOT NULL DEFAULT now(),
    update_by bigint,
    update_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE sys_role (
    role_id bigint PRIMARY KEY,
    role_name varchar(64) NOT NULL,
    role_key varchar(128) NOT NULL UNIQUE,
    entry_type varchar(16) NOT NULL,
    role_sort integer NOT NULL DEFAULT 0,
    data_scope char(1) NOT NULL DEFAULT '1',
    menu_check_strictly boolean NOT NULL DEFAULT true,
    dept_check_strictly boolean NOT NULL DEFAULT true,
    status char(1) NOT NULL DEFAULT '0',
    del_flag char(1) NOT NULL DEFAULT '0',
    remark varchar(500),
    create_dept bigint,
    create_by bigint,
    create_time timestamp NOT NULL DEFAULT now(),
    update_by bigint,
    update_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE sys_menu (
    menu_id bigint PRIMARY KEY,
    parent_id bigint NOT NULL DEFAULT 0,
    menu_name varchar(64) NOT NULL,
    order_num integer NOT NULL DEFAULT 0,
    path varchar(256) NOT NULL DEFAULT '',
    component varchar(256),
    query_param varchar(512),
    is_frame char(1) NOT NULL DEFAULT 'N',
    is_cache char(1) NOT NULL DEFAULT 'N',
    menu_type char(1) NOT NULL,
    visible char(1) NOT NULL DEFAULT '0',
    status char(1) NOT NULL DEFAULT '0',
    perms varchar(256),
    icon varchar(128),
    active_menu varchar(256),
    ext varchar(2000),
    remark varchar(500),
    create_dept bigint,
    create_by bigint,
    create_time timestamp NOT NULL DEFAULT now(),
    update_by bigint,
    update_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE sys_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE sys_role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE sys_post (
    post_id bigint PRIMARY KEY,
    dept_id bigint,
    post_code varchar(64) NOT NULL,
    post_name varchar(64) NOT NULL,
    post_category varchar(64),
    post_sort integer NOT NULL DEFAULT 0,
    status char(1) NOT NULL DEFAULT '0',
    del_flag char(1) NOT NULL DEFAULT '0',
    remark varchar(500),
    create_dept bigint,
    create_by bigint,
    create_time timestamp NOT NULL DEFAULT now(),
    update_by bigint,
    update_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE sys_user_post (
    user_id bigint NOT NULL,
    post_id bigint NOT NULL,
    PRIMARY KEY (user_id, post_id)
);

CREATE TABLE sys_login_info (
    info_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar(64),
    client_key varchar(128),
    device_type varchar(32),
    status char(1),
    ipaddr varchar(128),
    login_location varchar(255),
    browser varchar(128),
    os varchar(128),
    msg varchar(500),
    login_time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE sys_message (
    message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(64),
    type varchar(64),
    source varchar(64),
    title varchar(255),
    message varchar(2000),
    content text,
    data_json text,
    path varchar(512),
    send_user_ids varchar(2000),
    create_dept bigint,
    create_by bigint,
    create_time timestamp NOT NULL DEFAULT now(),
    update_by bigint,
    update_time timestamp NOT NULL DEFAULT now()
);

INSERT INTO sys_client (
    id, client_id, client_key, client_secret, grant_type, device_type,
    access_path, active_timeout, timeout, status, del_flag
) VALUES (
    1, 'certmuse-demo-web', 'certmuse-demo-web', 'local-demo-only', 'password', 'pc',
    '/**', 1800, 86400, '0', '0'
);

INSERT INTO sys_role (role_id, role_name, role_key, entry_type, role_sort, data_scope, status, del_flag)
VALUES (1, 'Demo Administrator', 'superadmin', 'ADMIN', 1, '1', '0', '0');

INSERT INTO sys_menu (menu_id, parent_id, menu_name, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms)
VALUES
    (1, 0, 'Dashboard', 1, 'index', 'index', 'N', 'N', 'C', '0', '0', 'certmuse:entry:admin'),
    (2, 0, 'System', 2, 'system', NULL, 'N', 'N', 'M', '0', '0', NULL),
    (3, 2, 'Users', 1, 'user', 'system/user/index', 'N', 'N', 'C', '0', '0', 'system:user:list');

INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1), (1, 2), (1, 3);

-- This hash is for the documented local-only password `certmuse-demo`.
-- Never replace it with a real credential.
INSERT INTO sys_user (
    user_id, user_name, nick_name, user_type, gender, password, status, del_flag
) VALUES (
    1, 'demo-admin', 'Demo Administrator', 'sys_user', '2',
    '$2a$10$CkaohZZKAvnN/9iy0/0KaurkixWWwnB0uT8cggoI8Ku4PxWWR2ijy', '0', '0'
);
