FROM postgres:16.14-alpine@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777

COPY backend/script/sql/postgres/postgres_ry_vue.sql /opt/certmuse/sql/00-postgres-ry-vue.sql
COPY backend/script/sql/postgres/postgres_ry_job.sql /opt/certmuse/sql/01-postgres-ry-job.sql
COPY backend/script/sql/postgres/certmuse/001_foundation.sql /opt/certmuse/sql/10-foundation.sql
COPY backend/script/sql/postgres/certmuse/002_content.sql /opt/certmuse/sql/11-content.sql
COPY backend/script/sql/postgres/certmuse/003_learning.sql /opt/certmuse/sql/12-learning.sql
COPY backend/script/sql/postgres/certmuse/004_profile.sql /opt/certmuse/sql/13-profile.sql
COPY backend/script/sql/postgres/certmuse/005_support.sql /opt/certmuse/sql/14-support.sql
COPY backend/script/sql/postgres/certmuse/006_constraints_indexes_seed.sql /opt/certmuse/sql/15-constraints-indexes-seed.sql
COPY backend/script/sql/postgres/certmuse/20260724_enable-minio-oss.sql /opt/certmuse/sql/20-enable-minio-oss.sql
COPY backend/script/sql/postgres/certmuse/20260724_hide-disabled-menus.sql /opt/certmuse/sql/21-hide-disabled-menus.sql
COPY backend/script/sql/postgres/certmuse/20260730_add-admin-content-menus.sql /opt/certmuse/sql/22-admin-content-menus.sql
COPY backend/script/sql/postgres/certmuse/20260730_knowledge-point-precheck-alignment.sql /opt/certmuse/sql/23-knowledge-point-precheck-alignment.sql
COPY backend/script/sql/postgres/certmuse/20260803_add-completed-import-batch-query-indexes.sql /opt/certmuse/sql/24-completed-import-batch-query-indexes.sql
COPY backend/script/sql/postgres/certmuse/20260803_add-question-import.sql /opt/certmuse/sql/25-add-question-import.sql
COPY backend/script/sql/postgres/certmuse/20260803_fix-knowledge-subject-order.sql /opt/certmuse/sql/26-fix-knowledge-subject-order.sql
COPY backend/script/sql/postgres/certmuse/20260803_question-import-q3-multisubject.sql /opt/certmuse/sql/27-question-import-q3-multisubject.sql
COPY backend/script/sql/postgres/certmuse/027_add-textbook-import.sql /opt/certmuse/sql/28-add-textbook-import.sql
COPY backend/script/sql/postgres/certmuse/20260804_add-qualification-version-management.sql /opt/certmuse/sql/29-add-qualification-version-management.sql
COPY backend/script/sql/postgres/certmuse/20260806_add-qualification-name-unique-index.sql /opt/certmuse/sql/30-add-qualification-name-unique-index.sql
COPY backend/script/sql/postgres/certmuse/20260804_add-textbook-management.sql /opt/certmuse/sql/30-add-textbook-management.sql
COPY backend/script/sql/postgres/certmuse/20260804_question-management-query-index.sql /opt/certmuse/sql/28-question-management-query-index.sql
COPY backend/script/sql/postgres/certmuse/20260804_question-management-rejected-reopen.sql /opt/certmuse/sql/29-question-management-rejected-reopen.sql
COPY backend/script/sql/postgres/certmuse/20260804_add-question-remove-permission.sql /opt/certmuse/sql/30-add-question-remove-permission.sql
COPY backend/script/sql/postgres/certmuse/20260804_rename-qualification-version-menu.sql /opt/certmuse/sql/31-rename-qualification-version-menu.sql
COPY backend/script/sql/postgres/certmuse/20260805_rename-admin-content-menus.sql /opt/certmuse/sql/32-rename-admin-content-menus.sql
COPY backend/script/sql/postgres/certmuse/20260805_hide-admin-content-import-menu.sql /opt/certmuse/sql/33-hide-admin-content-import-menu.sql
COPY backend/script/sql/postgres/certmuse/20260805_add-collection-management.sql /opt/certmuse/sql/34-add-collection-management.sql
COPY backend/script/sql/postgres/certmuse/20260805_collection-three-state-rollback.sql /opt/certmuse/sql/35-collection-three-state-model.sql
COPY backend/script/sql/postgres/certmuse/20260805_add-collection-draft-remove.sql /opt/certmuse/sql/36-add-collection-draft-remove.sql
COPY backend/script/sql/postgres/certmuse/20260806_remove-collection-publish-check.sql /opt/certmuse/sql/37-remove-collection-publish-check.sql
COPY backend/script/sql/postgres/certmuse/20260806_add-question-review-interfaces.sql /opt/certmuse/sql/38-add-question-review-interfaces.sql
COPY backend/script/sql/postgres/certmuse/20260806_add-question-submit-review-permission.sql /opt/certmuse/sql/39-add-question-submit-review-permission.sql
COPY backend/script/sql/postgres/certmuse/20260806_add-question-semantic-hash.sql /opt/certmuse/sql/40-add-question-semantic-hash.sql
COPY backend/script/sql/postgres/certmuse/20260806_reduce-question-statuses.sql /opt/certmuse/sql/41-reduce-question-statuses.sql
COPY backend/script/sql/postgres/certmuse/20260806_add-question-review-metadata.sql /opt/certmuse/sql/42-add-question-review-metadata.sql
COPY backend/script/sql/postgres/certmuse/20260806_backfill-high-qualification-subjects.sql /opt/certmuse/sql/43-backfill-high-qualification-subjects.sql
COPY backend/script/sql/postgres/certmuse/20260806_align-collection-review-contract.sql /opt/certmuse/sql/45-align-collection-review-contract.sql
COPY backend/script/sql/postgres/certmuse/20260806_add-collection-offline-permission.sql /opt/certmuse/sql/46-add-collection-offline-permission.sql
COPY backend/script/sql/postgres/certmuse/20260806_repair-collection-published-revisions.sql /opt/certmuse/sql/47-repair-collection-published-revisions.sql
COPY backend/script/sql/postgres/certmuse/20260807_collection-question-joint-review.sql /opt/certmuse/sql/48-collection-question-joint-review.sql
COPY backend/script/sql/postgres/certmuse/20260807_fix-question-offline-transition.sql /opt/certmuse/sql/49-fix-question-offline-transition.sql
COPY backend/script/sql/postgres/certmuse/20260807_allow-rejected-question-resubmission.sql /opt/certmuse/sql/50-allow-rejected-question-resubmission.sql
COPY backend/script/sql/postgres/certmuse/20260807_allow-rejected-question-resubmission-guard.sql /opt/certmuse/sql/51-allow-rejected-question-resubmission-guard.sql
COPY backend/script/sql/postgres/certmuse/20260807_add-knowledge-import-reconciliation.sql /opt/certmuse/sql/52-add-knowledge-import-reconciliation.sql
COPY backend/script/sql/postgres/certmuse/20260807_add-knowledge-point-row-version.sql /opt/certmuse/sql/53-add-knowledge-point-row-version.sql
COPY backend/script/sql/postgres/certmuse/20260807_repair-question-offline-transition.sql /opt/certmuse/sql/54-repair-question-offline-transition.sql
COPY backend/script/sql/postgres/certmuse/20260807_restore-rejected-question-resubmission.sql /opt/certmuse/sql/55-restore-rejected-question-resubmission.sql
COPY backend/script/sql/postgres/certmuse/20260807_allow-import-precheck-retry.sql /opt/certmuse/sql/56-allow-import-precheck-retry.sql
COPY backend/script/sql/postgres/certmuse/20260807_add-paper-import.sql /opt/certmuse/sql/57-add-paper-import.sql
COPY backend/script/sql/postgres/certmuse/20260807_fix-paper-import-batch-constraints.sql /opt/certmuse/sql/58-fix-paper-import-batch-constraints.sql
COPY backend/script/sql/postgres/certmuse/20260807_rename-syllabus-management-menu.sql /opt/certmuse/sql/59-rename-syllabus-management-menu.sql
COPY backend/script/sql/postgres/certmuse/20260807_backfill-initial-syllabus-versions.sql /opt/certmuse/sql/60-backfill-initial-syllabus-versions.sql
COPY backend/script/sql/postgres/certmuse/20260807_finalize-qualification-cascade-delete.sql /opt/certmuse/sql/61-finalize-qualification-cascade-delete.sql
COPY backend/script/sql/postgres/certmuse/20260811_add-auth-entry-model.sql /opt/certmuse/sql/62-add-auth-entry-model.sql
COPY backend/script/sql/postgres/certmuse/20260812_enforce-auth-entry-model.sql /opt/certmuse/sql/63-enforce-auth-entry-model.sql
COPY backend/script/sql/postgres/certmuse/ /opt/certmuse/migrations/
COPY backend/script/sql/postgres/certmuse/verify_local.sql /opt/certmuse/sql/99-verify.sql
COPY infra/docker/postgres/init.sh /docker-entrypoint-initdb.d/00-certmuse-init.sh

RUN chmod 0755 /docker-entrypoint-initdb.d/00-certmuse-init.sh
