<template>
  <div class="p-2 app-container certmuse-exam-schedule-page">
    <el-card shadow="hover" class="table-panel">
      <template #header>
        <div class="toolbar-shell">
          <div class="table-heading"><h3>官方考试安排</h3><p class="muted">在一个考期窗口内维护考试安排、考区报名并完成发布。</p></div>
          <div class="toolbar-actions"><el-button type="primary" plain icon="Plus" v-hasPermi="['certmuse:catalog:exam-schedule:create']" @click="openWorkspace()">新建考期</el-button><el-button icon="Refresh" circle title="刷新" @click="getList" /></div>
        </div>
      </template>
      <el-table v-loading="loading" border class="data-table" :data="periodList" row-key="id">
        <el-table-column label="考期" min-width="150"><template #default="{ row }"><el-link type="primary" underline="hover" @click="openWorkspace(row as ExamPeriodVO)">{{ row.periodCode }}</el-link><div class="muted">第 {{ row.revisionNo }} 版 · {{ row.half === 'H1' ? '上半年' : '下半年' }}</div></template></el-table-column>
        <el-table-column label="官方来源" min-width="260" show-overflow-tooltip><template #default="{ row }"><el-link :href="row.officialSourceUrl" target="_blank" type="primary" underline="hover">查看官方公告</el-link><div class="muted">发布于 {{ formatDate(row.sourcePublishedAt) }}</div></template></el-table-column>
        <el-table-column label="配置情况" min-width="210"><template #default="{ row }">{{ row.scheduleCount }} 项资格安排 · {{ row.registrationCount }} 个考区报名</template></el-table-column>
        <el-table-column label="状态" width="100" align="center"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column>
        <el-table-column label="操作" fixed="right" width="130" align="center"><template #default="{ row }"><el-tooltip content="打开考期"><el-button link type="primary" icon="View" @click="openWorkspace(row as ExamPeriodVO)" /></el-tooltip><el-tooltip v-if="row.status === 'draft'" content="删除草稿"><el-button link type="danger" icon="Delete" v-hasPermi="['certmuse:catalog:exam-schedule:edit']" @click="handleDeletePeriod(row as ExamPeriodVO)" /></el-tooltip><el-tooltip v-else-if="row.status === 'published'" content="新建修订"><el-button link type="primary" icon="DocumentCopy" v-hasPermi="['certmuse:catalog:exam-schedule:create']" @click="handleRevision(row as ExamPeriodVO)" /></el-tooltip></template></el-table-column>
      </el-table>
    </el-card>

    <el-drawer v-model="workspaceDrawer" :title="workspaceTitle" size="min(1080px, 96%)" destroy-on-close @closed="resetWorkspace">
      <el-form ref="periodFormRef" :model="periodForm" :rules="periodRules" label-position="top" class="workspace-form">
        <section class="workspace-section">
          <div class="section-heading"><div><h3>考期与官方来源</h3><p>先保存为草稿，再继续补充安排和报名。</p></div><el-tag v-if="selectedPeriod" :type="statusType(selectedPeriod.status)">{{ statusLabel(selectedPeriod.status) }}</el-tag></div>
          <div class="form-grid"><el-form-item label="考试年份" prop="examYear"><el-input-number v-model="periodForm.examYear" :disabled="Boolean(selectedPeriod)" :min="currentYear" :max="currentYear + 3" controls-position="right" /></el-form-item><el-form-item label="半年度" prop="half"><el-select v-model="periodForm.half" :disabled="Boolean(selectedPeriod)"><el-option label="上半年" value="H1" /><el-option label="下半年" value="H2" /></el-select></el-form-item></div>
          <el-form-item label="官方安排来源" prop="officialSourceUrl"><el-input v-model="periodForm.officialSourceUrl" :disabled="!canEdit" placeholder="https://..." /></el-form-item><el-form-item label="来源发布日期" prop="sourcePublishedAt"><el-date-picker v-model="periodForm.sourcePublishedAt" :disabled="!canEdit" type="date" value-format="YYYY-MM-DD" placeholder="选择官方发布日期" /></el-form-item>
          <div v-if="canEdit" class="section-actions"><el-button type="primary" :loading="savingPeriod" @click="savePeriod">{{ selectedPeriod ? '保存考期信息' : '保存并继续配置' }}</el-button></div>
        </section>
      </el-form>

      <template v-if="selectedPeriod">
        <section class="workspace-section">
          <div class="section-heading"><div><h3>资格与考试场次</h3><p>每项资格一次填写全部考试场次。</p></div><el-button v-if="canEdit && !scheduleEditor.open" type="primary" plain icon="Plus" @click="openScheduleEditor()">添加资格</el-button></div>
          <el-empty v-if="!selectedPeriod.schedules.length && !scheduleEditor.open" description="尚未添加资格安排" :image-size="72" />
          <div v-else class="item-list"><article v-for="schedule in selectedPeriod.schedules" :key="schedule.id" class="item-card"><div class="item-card-heading"><div><strong>{{ schedule.certificationName }}</strong><span>{{ formatExamDate(schedule.examStartDate) }} 至 {{ formatExamDate(schedule.examEndDate) }}</span></div><el-button v-if="canEdit" link type="primary" icon="Edit" @click="openScheduleEditor(schedule)">编辑</el-button></div><div v-for="session in schedule.sessions" :key="session.id ?? session.examSubjectId" class="session-summary">{{ session.subjectName ?? session.examSubjectId }} · {{ session.sessionCode }} · {{ formatDateTime(session.startTime) }}—{{ formatTime(session.endTime) }}</div><p v-if="schedule.publicNote" class="item-note">{{ schedule.publicNote }}</p><el-button v-if="canEdit" link type="danger" icon="Delete" @click="handleDeleteSchedule(schedule)">删除资格安排</el-button></article></div>
          <el-form v-if="scheduleEditor.open" ref="scheduleFormRef" :model="scheduleForm" :rules="scheduleRules" label-position="top" class="inline-editor"><div class="editor-heading"><h4>{{ scheduleEditor.id ? '编辑资格安排' : '添加资格安排' }}</h4><el-button link @click="closeScheduleEditor">收起</el-button></div><el-form-item label="考试资格" prop="certificationId"><el-select v-model="scheduleForm.certificationId" filterable :disabled="Boolean(scheduleEditor.id)" placeholder="请选择资格" @change="loadSubjectOptions"><el-option v-for="item in qualificationOptions" :key="item.id" :label="item.certificationName" :value="item.id" /></el-select></el-form-item><el-form-item label="公开说明"><el-input v-model="scheduleForm.publicNote" type="textarea" :rows="2" maxlength="500" show-word-limit /></el-form-item><div class="editor-heading"><h4>考试场次</h4><el-button type="primary" link icon="Plus" @click="addSession">添加场次</el-button></div><div v-for="(session, index) in scheduleForm.sessions" :key="index" class="session-row"><el-select v-model="session.examSubjectId" filterable placeholder="考试科目"><el-option v-for="subject in subjectOptions" :key="subject.id" :label="subject.label" :value="subject.id" /></el-select><el-input v-model="session.sessionCode" placeholder="场次编码" /><el-date-picker v-model="session.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" placeholder="开始时间" /><el-date-picker v-model="session.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" placeholder="结束时间" /><el-button type="danger" link icon="Delete" :disabled="scheduleForm.sessions.length === 1" @click="removeSession(index)" /></div><el-alert v-if="subjectLoadFailed" title="科目选项暂时无法读取，请确认账号拥有内容导入查询权限。" type="warning" :closable="false" show-icon /><div class="section-actions"><el-button @click="closeScheduleEditor">取消</el-button><el-button type="primary" :loading="savingSchedule" @click="submitSchedule">保存资格安排</el-button></div></el-form>
        </section>

        <section class="workspace-section">
          <div class="section-heading"><div><h3>考区报名</h3><p>仅选择启用考区；长期入口通常无需在每个考期重复维护。</p></div><el-button v-if="canEdit && !registrationEditor.open" type="primary" plain icon="Plus" @click="openRegistrationEditor()">添加考区报名</el-button></div>
          <el-empty v-if="!selectedPeriod.registrations.length && !registrationEditor.open" description="尚未添加考区报名信息" :image-size="72" />
          <div v-else class="item-list"><article v-for="registration in selectedPeriod.registrations" :key="registration.id" class="item-card"><div class="item-card-heading"><div><strong>{{ registration.regionName }}</strong><span>{{ timeRange(registration.registrationStart, registration.registrationEnd) }}</span></div><el-button v-if="canEdit" link type="primary" icon="Edit" @click="openRegistrationEditor(registration)">编辑</el-button></div><el-link :href="registration.officialSourceUrl" target="_blank" type="primary">查看官方通知</el-link><el-button v-if="canEdit" link type="danger" icon="Delete" @click="deleteRegistration(registration)">删除报名信息</el-button></article></div>
          <el-form v-if="registrationEditor.open" ref="registrationFormRef" :model="registrationForm" :rules="registrationRules" label-position="top" class="inline-editor"><div class="editor-heading"><h4>{{ registrationEditor.id ? '编辑考区报名' : '添加考区报名' }}</h4><el-button link @click="closeRegistrationEditor">收起</el-button></div><div class="form-grid"><el-form-item label="考区" prop="regionId"><el-select v-model="registrationForm.regionId" filterable :disabled="Boolean(registrationEditor.id)" placeholder="请选择考区"><el-option v-for="item in enabledRegions" :key="item.id" :label="item.regionName" :value="item.id" /></el-select></el-form-item><el-form-item label="来源发布日期" prop="sourcePublishedAt"><el-date-picker v-model="registrationForm.sourcePublishedAt" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="报名开始（可空）"><el-date-picker v-model="registrationForm.registrationStart" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" clearable /></el-form-item><el-form-item label="报名截止" prop="registrationEnd"><el-date-picker v-model="registrationForm.registrationEnd" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" /></el-form-item></div><el-form-item label="官方报名通知" prop="officialSourceUrl"><el-input v-model="registrationForm.officialSourceUrl" placeholder="https://..." /></el-form-item><el-collapse><el-collapse-item title="审核与缴费信息（可选）" name="supplementary"><div class="form-grid"><el-form-item label="审核开始"><el-date-picker v-model="registrationForm.reviewStart" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" clearable /></el-form-item><el-form-item label="审核结束"><el-date-picker v-model="registrationForm.reviewEnd" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" clearable /></el-form-item><el-form-item label="缴费开始"><el-date-picker v-model="registrationForm.paymentStart" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" clearable /></el-form-item><el-form-item label="缴费结束"><el-date-picker v-model="registrationForm.paymentEnd" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" clearable /></el-form-item></div><el-form-item label="资格审核说明"><el-input v-model="registrationForm.qualificationReviewNote" type="textarea" :rows="2" maxlength="500" show-word-limit /></el-form-item><el-form-item label="缴费说明"><el-input v-model="registrationForm.paymentNote" type="textarea" :rows="2" maxlength="500" show-word-limit /></el-form-item></el-collapse-item></el-collapse><div class="section-actions"><el-button @click="closeRegistrationEditor">取消</el-button><el-button type="primary" :loading="savingRegistration" @click="submitRegistration">保存考区报名</el-button></div></el-form>
          <el-button v-if="canEdit" link type="primary" @click="openRegionDirectory">维护考区长期入口</el-button>
        </section>
      </template>
      <template #footer><div class="workspace-footer"><span v-if="selectedPeriod" class="muted">{{ selectedPeriod.schedules.length }} 项资格安排 · {{ selectedPeriod.registrations.length }} 个考区报名</span><div><el-button @click="workspaceDrawer = false">关闭</el-button><el-button v-if="selectedPeriod?.status === 'draft'" type="success" :loading="publishing" v-hasPermi="['certmuse:catalog:exam-schedule:publish']" @click="publishWorkspace">发布考期</el-button></div></div></template>
    </el-drawer>
    <el-dialog v-model="regionDialog" title="维护考区长期入口" width="620px" append-to-body destroy-on-close>
      <el-form ref="regionFormRef" :model="regionForm" :rules="regionRules" label-position="top">
        <el-form-item label="考区"><el-select v-model="selectedRegionId" filterable placeholder="请选择考区" @change="selectRegion"><el-option v-for="region in regionOptions" :key="region.id" :label="region.regionName" :value="region.id" /></el-select></el-form-item>
        <template v-if="selectedRegionId"><el-form-item label="实施机构"><el-input v-model="regionForm.institutionName" maxlength="300" /></el-form-item><el-form-item label="联系电话"><el-input v-model="regionForm.contactPhone" maxlength="50" /></el-form-item><el-form-item label="长期入口" prop="localNoticeUrl"><el-input v-model="regionForm.localNoticeUrl" placeholder="https://..." /></el-form-item></template>
      </el-form>
      <template #footer><el-button @click="regionDialog = false">取消</el-button><el-button type="primary" :disabled="!selectedRegionId" :loading="savingRegion" @click="submitRegion">保存</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup name="CertmuseExamSchedule" lang="ts">
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus';
import { computed, onMounted, reactive, ref } from 'vue';
import type { ExamSubjectOptionVO } from '@/api/certmuse/catalog/import/types';
import type { QualificationVO } from '@/api/certmuse/catalog/subject-version';
import type { ExamGuidanceStatus, ExamPeriodCreateForm, ExamPeriodDetailVO, ExamPeriodVO, ExamRegionRegistrationForm, ExamRegionRegistrationVO, ExamRegionUpdateForm, ExamRegionVO, ExamScheduleForm, ExamScheduleVO } from '@/api/certmuse/catalog/exam-guidance';
import { createExamPeriod, createExamPeriodRevision, createExamRegionRegistration, createExamSchedule, deleteExamPeriod, deleteExamRegionRegistration, deleteExamSchedule, getExamPeriod, listExamPeriods, listExamRegions, publishExamPeriod, updateExamPeriod, updateExamRegion, updateExamRegionRegistration, updateExamSchedule } from '@/api/certmuse/catalog/exam-guidance';
import { getImportContextOptions } from '@/api/certmuse/catalog/import';
import { listQualifications } from '@/api/certmuse/catalog/subject-version';

interface PeriodEditor extends ExamPeriodCreateForm { expectedRowVersion: number }
const currentYear = new Date().getFullYear();
const periodFormRef = ref<FormInstance>(); const scheduleFormRef = ref<FormInstance>(); const registrationFormRef = ref<FormInstance>(); const regionFormRef = ref<FormInstance>();
const loading = ref(false); const savingPeriod = ref(false); const savingSchedule = ref(false); const savingRegistration = ref(false); const savingRegion = ref(false); const publishing = ref(false); const workspaceDrawer = ref(false); const regionDialog = ref(false);
const periodList = ref<ExamPeriodVO[]>([]); const selectedPeriod = ref<ExamPeriodDetailVO>(); const qualificationOptions = ref<QualificationVO[]>([]); const subjectOptions = ref<ExamSubjectOptionVO[]>([]); const enabledRegions = ref<ExamRegionVO[]>([]); const regionOptions = ref<ExamRegionVO[]>([]); const selectedRegionId = ref(''); const subjectLoadFailed = ref(false);
const queryParams = reactive({ pageNum: 1, pageSize: 20 }); const periodForm = reactive<PeriodEditor>(emptyPeriod()); const scheduleForm = reactive<ExamScheduleForm>(emptySchedule()); const registrationForm = reactive<ExamRegionRegistrationForm>(emptyRegistration()); const regionForm = reactive<ExamRegionUpdateForm>(emptyRegion()); const scheduleEditor = reactive({ open: false, id: '' }); const registrationEditor = reactive({ open: false, id: '' });
const required = { required: true, message: '此项不能为空', trigger: 'change' } as const;
const periodRules: FormRules<PeriodEditor> = { examYear: [required], half: [required], officialSourceUrl: [required, { type: 'url', message: '请输入有效的 HTTPS 地址', trigger: 'blur' }], sourcePublishedAt: [required] };
const scheduleRules: FormRules<ExamScheduleForm> = { certificationId: [required] };
const registrationRules: FormRules<ExamRegionRegistrationForm> = { regionId: [required], registrationEnd: [required], officialSourceUrl: [required, { type: 'url', message: '请输入有效的 HTTPS 地址', trigger: 'blur' }], sourcePublishedAt: [required] };
const regionRules: FormRules<ExamRegionUpdateForm> = { localNoticeUrl: [required, { type: 'url', message: '请输入有效地址', trigger: 'blur' }] };
const canEdit = computed(() => !selectedPeriod.value || selectedPeriod.value.status === 'draft'); const workspaceTitle = computed(() => selectedPeriod.value ? `维护 ${selectedPeriod.value.periodCode}` : '新建考试期次');
function emptyPeriod(): PeriodEditor { return { periodCode: `${currentYear}-H1`, examYear: currentYear, half: 'H1', officialSourceUrl: '', sourcePublishedAt: '', expectedRowVersion: 0 }; }
function emptySchedule(): ExamScheduleForm { return { certificationId: '', publicNote: '', sessions: [{ examSubjectId: '', sessionCode: '', startTime: '', endTime: '', sortOrder: 1 }], expectedPeriodRowVersion: 0 }; }
function emptyRegistration(): ExamRegionRegistrationForm { return { regionId: '', registrationStart: null, registrationEnd: '', reviewStart: null, reviewEnd: null, paymentStart: null, paymentEnd: null, qualificationReviewNote: '', paymentNote: '', officialSourceUrl: '', sourcePublishedAt: '', expectedPeriodRowVersion: 0 }; }
function emptyRegion(): ExamRegionUpdateForm { return { institutionName: '', contactPhone: '', localNoticeUrl: '', sortOrder: 0, status: 'enabled', expectedRowVersion: 0 }; }
async function getList() { loading.value = true; try { periodList.value = (await listExamPeriods(queryParams)).data.rows; } catch (error) { ElMessage.error(errorMessage(error, '考期列表加载失败')); } finally { loading.value = false; } }
async function openWorkspace(row?: ExamPeriodVO) { workspaceDrawer.value = true; closeEditors(); if (!row) { selectedPeriod.value = undefined; Object.assign(periodForm, emptyPeriod()); return; } try { selectedPeriod.value = (await getExamPeriod(row.id)).data; fillPeriodForm(selectedPeriod.value); } catch (error) { ElMessage.error(errorMessage(error, '考期详情加载失败')); } }
function resetWorkspace() { selectedPeriod.value = undefined; closeEditors(); Object.assign(periodForm, emptyPeriod()); }
function fillPeriodForm(period: ExamPeriodDetailVO) { Object.assign(periodForm, { periodCode: period.periodCode, examYear: period.examYear, half: period.half, officialSourceUrl: period.officialSourceUrl, sourcePublishedAt: dateValue(period.sourcePublishedAt), expectedRowVersion: period.rowVersion }); }
async function savePeriod() { if (!(await periodFormRef.value?.validate().catch(() => false))) return; savingPeriod.value = true; try { if (selectedPeriod.value) selectedPeriod.value = (await updateExamPeriod(selectedPeriod.value.id, { officialSourceUrl: periodForm.officialSourceUrl, sourcePublishedAt: sourceDateTime(periodForm.sourcePublishedAt), expectedRowVersion: selectedPeriod.value.rowVersion })).data; else selectedPeriod.value = (await createExamPeriod({ periodCode: `${periodForm.examYear}-${periodForm.half}`, examYear: periodForm.examYear, half: periodForm.half, officialSourceUrl: periodForm.officialSourceUrl, sourcePublishedAt: sourceDateTime(periodForm.sourcePublishedAt) })).data; fillPeriodForm(selectedPeriod.value); await getList(); ElMessage.success('考期已保存，可继续配置'); } catch (error) { ElMessage.error(errorMessage(error, '考期保存失败')); } finally { savingPeriod.value = false; } }
async function refreshDetail() { if (selectedPeriod.value) { selectedPeriod.value = (await getExamPeriod(selectedPeriod.value.id)).data; fillPeriodForm(selectedPeriod.value); } }
async function loadQualifications() { qualificationOptions.value = (await listQualifications({ qualificationLevel: 'HIGH', status: '0', pageNum: 1, pageSize: 100 })).data.rows; }
async function loadSubjectOptions(certificationId: string) { subjectOptions.value = []; subjectLoadFailed.value = false; if (!certificationId) return; try { subjectOptions.value = (await getImportContextOptions(undefined, certificationId)).examSubjects; } catch { subjectLoadFailed.value = true; } }
async function openScheduleEditor(row?: ExamScheduleVO) { if (!selectedPeriod.value) return; if (!qualificationOptions.value.length) { try { await loadQualifications(); } catch (error) { ElMessage.error(errorMessage(error, '资格选项加载失败')); return; } } Object.assign(scheduleForm, row ? { certificationId: row.certificationId, publicNote: row.publicNote ?? '', sessions: row.sessions.map(item => ({ examSubjectId: item.examSubjectId, sessionCode: item.sessionCode, startTime: item.startTime, endTime: item.endTime, sortOrder: item.sortOrder })), expectedPeriodRowVersion: selectedPeriod.value.rowVersion } : { ...emptySchedule(), expectedPeriodRowVersion: selectedPeriod.value.rowVersion }); scheduleEditor.id = row?.id ?? ''; scheduleEditor.open = true; await loadSubjectOptions(scheduleForm.certificationId); }
function closeScheduleEditor() { scheduleEditor.open = false; scheduleEditor.id = ''; subjectOptions.value = []; }
function addSession() { scheduleForm.sessions.push({ examSubjectId: '', sessionCode: '', startTime: '', endTime: '', sortOrder: scheduleForm.sessions.length + 1 }); }
function removeSession(index: number) { scheduleForm.sessions.splice(index, 1); }
async function submitSchedule() { if (!(await scheduleFormRef.value?.validate().catch(() => false)) || !selectedPeriod.value) return; if (!scheduleForm.sessions.every(item => item.examSubjectId && item.sessionCode && item.startTime && item.endTime && item.endTime > item.startTime)) { ElMessage.warning('请完整填写场次，且结束时间必须晚于开始时间'); return; } savingSchedule.value = true; try { const payload: ExamScheduleForm = { ...scheduleForm, sessions: scheduleForm.sessions.map(item => ({ ...item, sessionCode: item.sessionCode.trim().toUpperCase() })), expectedPeriodRowVersion: selectedPeriod.value.rowVersion }; if (scheduleEditor.id) await updateExamSchedule(scheduleEditor.id, payload); else await createExamSchedule(selectedPeriod.value.id, payload); await Promise.all([refreshDetail(), getList()]); closeScheduleEditor(); ElMessage.success('资格安排已保存'); } catch (error) { ElMessage.error(errorMessage(error, '资格安排保存失败')); } finally { savingSchedule.value = false; } }
async function handleDeleteSchedule(row: ExamScheduleVO) { if (!selectedPeriod.value) return; try { await ElMessageBox.confirm(`确定删除“${row.certificationName}”的考试安排吗？`, '删除资格安排', { type: 'warning' }); await deleteExamSchedule(row.id, selectedPeriod.value.rowVersion); await Promise.all([refreshDetail(), getList()]); ElMessage.success('资格安排已删除'); } catch (error) { if (!isCancel(error)) ElMessage.error(errorMessage(error, '删除资格安排失败')); } }
async function loadEnabledRegions() { enabledRegions.value = (await listExamRegions({ pageNum: 1, pageSize: 100, status: 'enabled' })).data.rows; }
async function openRegionDirectory() { try { regionOptions.value = (await listExamRegions({ pageNum: 1, pageSize: 100 })).data.rows; selectedRegionId.value = ''; Object.assign(regionForm, emptyRegion()); regionDialog.value = true; } catch (error) { ElMessage.error(errorMessage(error, '考区目录加载失败')); } }
function selectRegion(regionId: string) { const region = regionOptions.value.find(item => item.id === regionId); if (region) Object.assign(regionForm, { institutionName: region.institutionName ?? '', contactPhone: region.contactPhone ?? '', localNoticeUrl: region.localNoticeUrl, sortOrder: region.sortOrder, status: region.status, expectedRowVersion: region.rowVersion }); }
async function submitRegion() { if (!(await regionFormRef.value?.validate().catch(() => false))) return; savingRegion.value = true; try { await updateExamRegion(selectedRegionId.value, regionForm); regionDialog.value = false; enabledRegions.value = []; ElMessage.success('考区长期入口已保存'); } catch (error) { ElMessage.error(errorMessage(error, '考区长期入口保存失败')); } finally { savingRegion.value = false; } }
async function openRegistrationEditor(row?: ExamRegionRegistrationVO) { if (!selectedPeriod.value) return; if (!enabledRegions.value.length) { try { await loadEnabledRegions(); } catch (error) { ElMessage.error(errorMessage(error, '考区选项加载失败')); return; } } Object.assign(registrationForm, row ? { regionId: row.regionId, registrationStart: row.registrationStart ?? null, registrationEnd: row.registrationEnd, reviewStart: row.reviewStart ?? null, reviewEnd: row.reviewEnd ?? null, paymentStart: row.paymentStart ?? null, paymentEnd: row.paymentEnd ?? null, qualificationReviewNote: row.qualificationReviewNote ?? '', paymentNote: row.paymentNote ?? '', officialSourceUrl: row.officialSourceUrl, sourcePublishedAt: dateValue(row.sourcePublishedAt), expectedPeriodRowVersion: selectedPeriod.value.rowVersion } : { ...emptyRegistration(), expectedPeriodRowVersion: selectedPeriod.value.rowVersion }); registrationEditor.id = row?.id ?? ''; registrationEditor.open = true; }
function closeRegistrationEditor() { registrationEditor.open = false; registrationEditor.id = ''; }
async function submitRegistration() { if (!(await registrationFormRef.value?.validate().catch(() => false)) || !selectedPeriod.value) return; if (!validOptionalRange(registrationForm.reviewStart, registrationForm.reviewEnd) || !validOptionalRange(registrationForm.paymentStart, registrationForm.paymentEnd)) { ElMessage.warning('审核和缴费时间必须成对填写，且结束时间晚于开始时间'); return; } if (registrationForm.registrationStart && registrationForm.registrationStart >= registrationForm.registrationEnd) { ElMessage.warning('报名截止时间必须晚于报名开始时间'); return; } savingRegistration.value = true; try { const payload: ExamRegionRegistrationForm = { ...registrationForm, sourcePublishedAt: sourceDateTime(registrationForm.sourcePublishedAt), expectedPeriodRowVersion: selectedPeriod.value.rowVersion }; if (registrationEditor.id) await updateExamRegionRegistration(registrationEditor.id, payload); else await createExamRegionRegistration(selectedPeriod.value.id, payload); await Promise.all([refreshDetail(), getList()]); closeRegistrationEditor(); ElMessage.success('考区报名信息已保存'); } catch (error) { ElMessage.error(errorMessage(error, '考区报名信息保存失败')); } finally { savingRegistration.value = false; } }
async function deleteRegistration(row: ExamRegionRegistrationVO) { if (!selectedPeriod.value) return; try { await ElMessageBox.confirm(`确定删除“${row.regionName}”的报名信息吗？`, '删除报名信息', { type: 'warning' }); await deleteExamRegionRegistration(row.id, selectedPeriod.value.rowVersion); await Promise.all([refreshDetail(), getList()]); ElMessage.success('考区报名信息已删除'); } catch (error) { if (!isCancel(error)) ElMessage.error(errorMessage(error, '删除报名信息失败')); } }
async function publishWorkspace() { if (!selectedPeriod.value) return; const blockers: string[] = []; if (!selectedPeriod.value.schedules.length) blockers.push('至少一项资格安排'); if (!selectedPeriod.value.schedules.some(item => item.sessions.length)) blockers.push('至少一个考试场次'); if (!selectedPeriod.value.registrations.length) blockers.push('至少一条考区报名信息'); if (blockers.length) { ElMessage.warning(`发布前请先完成：${blockers.join('、')}。`); return; } try { await ElMessageBox.confirm(`发布 ${selectedPeriod.value.periodCode} 第 ${selectedPeriod.value.revisionNo} 版后不能直接修改，是否继续？`, '发布考期', { type: 'warning' }); publishing.value = true; await publishExamPeriod(selectedPeriod.value.id, selectedPeriod.value.rowVersion); await Promise.all([refreshDetail(), getList()]); ElMessage.success('考期已发布'); } catch (error) { if (!isCancel(error)) ElMessage.error(errorMessage(error, '发布失败，请检查资格场次和考区报名信息')); } finally { publishing.value = false; } }
async function handleRevision(row: ExamPeriodVO) { try { await ElMessageBox.confirm(`基于 ${row.periodCode} 第 ${row.revisionNo} 版创建修订草稿吗？`, '创建修订', { type: 'warning' }); selectedPeriod.value = (await createExamPeriodRevision(row.id, row.rowVersion)).data; fillPeriodForm(selectedPeriod.value); workspaceDrawer.value = true; await getList(); ElMessage.success('修订草稿已创建'); } catch (error) { if (!isCancel(error)) ElMessage.error(errorMessage(error, '创建修订失败')); } }
async function handleDeletePeriod(row: ExamPeriodVO) { try { await ElMessageBox.confirm(`确定删除考期草稿 ${row.periodCode} 吗？`, '删除考期', { type: 'warning' }); await deleteExamPeriod(row.id, row.rowVersion); await getList(); ElMessage.success('考期草稿已删除'); } catch (error) { if (!isCancel(error)) ElMessage.error(errorMessage(error, '删除考期失败')); } }
function closeEditors() { closeScheduleEditor(); closeRegistrationEditor(); }
function validOptionalRange(start?: string | null, end?: string | null) { return (!start && !end) || Boolean(start && end && end > start); }
function statusLabel(status: ExamGuidanceStatus) { return { draft: '草稿', published: '已发布', superseded: '已替代' }[status]; }
function statusType(status: ExamGuidanceStatus) { return status === 'published' ? 'success' : status === 'superseded' ? 'info' : 'warning'; }
function formatDate(value?: string | null) { return value ? dateValue(value) : '—'; } function formatExamDate(value?: string | null) { return value ? new Date(value).toLocaleDateString('zh-CN', { timeZone: 'Asia/Shanghai' }) : '—'; } function formatDateTime(value?: string | null) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '—'; } function formatTime(value?: string | null) { return value ? new Date(value).toLocaleTimeString('zh-CN', { hour12: false, hour: '2-digit', minute: '2-digit' }) : '—'; } function timeRange(start?: string | null, end?: string | null) { return start && end ? `${formatDateTime(start)} 至 ${formatDateTime(end)}` : '未公布'; } function dateValue(value?: string | null) { return value?.slice(0, 10) ?? ''; } function sourceDateTime(value: string) { return `${value}T00:00:00+08:00`; } function errorMessage(error: unknown, fallback: string) { return error instanceof Error && error.message ? error.message : fallback; } function isCancel(error: unknown) { return error === 'cancel' || error === 'close'; }
onMounted(() => void getList());
</script>

<style scoped lang="scss">
@use '@/assets/styles/components/page-shell' as pageShell;
@include pageShell.table-crud-page;
.workspace-form { padding-right: 2px; }.workspace-section { padding: 0 4px 24px; margin-bottom: 24px; border-bottom: 1px solid var(--el-border-color-lighter); }.workspace-section:last-child { border-bottom: 0; }.section-heading, .item-card-heading, .editor-heading, .workspace-footer { display: flex; align-items: center; justify-content: space-between; gap: 16px; }.section-heading { margin-bottom: 14px; }.section-heading h3, .section-heading p, .editor-heading h4 { margin: 0; }.section-heading p, .muted, .item-card-heading span, .item-note { color: var(--el-text-color-secondary); font-size: 13px; }.section-heading p { margin-top: 4px; }.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0 16px; }.section-actions { display: flex; justify-content: flex-end; gap: 8px; margin-top: 12px; }.item-list { display: grid; gap: 10px; }.item-card, .inline-editor { padding: 16px; border: 1px solid var(--el-border-color-lighter); border-radius: 8px; background: var(--el-fill-color-lighter); }.item-card-heading strong, .item-card-heading span { display: block; }.item-card-heading span { margin-top: 4px; }.session-summary { margin-top: 8px; font-size: 13px; }.item-note { margin: 10px 0; }.inline-editor { margin-top: 12px; background: var(--el-bg-color); }.editor-heading { margin-bottom: 12px; }.session-row { display: grid; grid-template-columns: 1fr .65fr 1.2fr 1.2fr auto; gap: 8px; align-items: center; margin-bottom: 10px; }.workspace-footer { width: 100%; }.workspace-footer > div { display: flex; gap: 8px; }:deep(.el-select), :deep(.el-date-editor), :deep(.el-input-number) { width: 100%; } @media (max-width: 760px) { .form-grid, .session-row { grid-template-columns: 1fr; }.section-heading, .workspace-footer { align-items: flex-start; flex-direction: column; }.workspace-footer > div { align-self: flex-end; } }
</style>
